### ISSUE TITLE
Old master branch in this repository

### ISSUE THREAD

**Issue by eregon** [actions/starter-workflows#1001]
This repository has an old master branch:
https://github.com/actions/starter-workflows/tree/master

Which may be confused with the maintained `main` branch.
This can be confusing, especially when following existing links.

I think it would be best to remove the `master` branch, or somehow make it redirect to the `main` branch.

There also seems to be some commits in `master` not in `main`: https://github.com/actions/starter-workflows/compare/master

**Comment by andymckay** [comment]
Thanks, good point, removed that branch.
