### ISSUE TITLE
Please say somewhere that the "$default-branch" in the templates is not valid Workflow syntax

### ISSUE THREAD

**Issue by hugomg** [actions/starter-workflows#1025]
The programming language I am using doesn't have a starter workflow, so I came here to look at the workflow for other languages to figure out how I should structure my own workflows. One thing that caught me unaware is that the `$default-branch` syntax that is present in most of the examples isn't actually valid workflow syntax. It is only valid for workflow templates and cannot be copied verbatim into regular workflow files.

```yaml
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
```

I would appreciate if there could be some kind of warning or documentation saying that the `$default-branch` notation is not valid workflow syntax. Perhaps there should be a comment, or at least a message in the README.

One possible way to implement this would be to add a special comment to the top of every template file, and then remove this comment when the template is expanded.

**Comment by amarvin** [comment]
Same for me. Wasted an hour. Even GitHub docs seem to indicate that `$default-branch` is allowed (https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/).

**Comment by 965022-oss** [comment]
The default branch could directly run workflows by GitHub Actions was used on dependencies, I used it on merging my default branch CodeQL as workflow running on every template on the table.
Although update was unable on the fork repository to stream with the latest version.
