### ISSUE TITLE
CodeQL workflow: invalid `cron` attribute "$cron-weekly"

### ISSUE THREAD

**Issue by ScottBrenner** [actions/starter-workflows#1143]
https://github.com/actions/starter-workflows/blob/15daabeaa4dd4e5c5815a0f056ebb79fac568129/code-scanning/codeql.yml#L21 reports 
> invalid `cron` attribute "$cron-weekly"

(https://github.com/ScottBrenner/cfn-lint-action/actions/runs/1287680746)

From https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule:

> Note: GitHub Actions does not support the non-standard syntax @yearly, @monthly, @weekly, @daily, @hourly, and @reboot.

**Comment by ScottBrenner** [comment]
Yes

**Comment by KhushalPShah** [comment]
@ScottBrenner 
Just to confirm once, all I need to do is write : 
- cron: '0 0 * * 0' 
instead of the existing line, right?
