### ISSUE TITLE
Unable to install Android SDK Build-Tools without sudo.

### ISSUE THREAD

**Issue by tetedoie** [actions/starter-workflows#119]
https://github.com/actions/starter-workflows/blob/dcaa948ed3751fbfc4285b4745799dc2a5d4476e/ci/android.yml#L17

Without sudo, the gradle build command is failing with the following error.

<img width="844" alt="Screen Shot 2019-09-13 at 3 05 49 PM" src="https://user-images.githubusercontent.com/23039961/64897412-365ba880-d638-11e9-9923-3057e852e369.png">

`sudo ./gradlew build` works.

<img width="788" alt="Screen Shot 2019-09-13 at 3 29 10 PM" src="https://user-images.githubusercontent.com/23039961/64898260-4aed7000-d63b-11e9-878e-8a4a2b51c20f.png">

**Comment by andymckay** [comment]
It looks like based on https://github.com/actions/starter-workflows/issues/58 that this issue is now fixed, so I'm closing this duplicate. If that's incorrect @tetedoie please let me know. Thank you 🙇

**Comment by guillaume-tgl** [comment]
Is this really fixed? Is it now possible to install an Android component without sudo or will it fail again when the next version of a component is missing from your image?

**Comment by tetedoie** [comment]
@guillaume-tgl  It should work now. I'll text and confirm asap.

**Comment by jcayzac** [comment]
For anybody coming here, here's a fix until the problem really gets resolved:

```yaml
- name: 'Temporary hack for starter-workflows/issues#119'
  run: yes | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager 'platforms;android-R'
```

Note that `sudo chown -R runner /usr/local/lib/android/sdk` also works, but takes much longer. `sdkmanager` really should just be setuid'ed.
