### ISSUE TITLE
Remove scan extension from code scanning

### ISSUE THREAD

**Issue by prabhu** [actions/starter-workflows#1211]
Hello,

I would like to remove the scan extension from the code scanning marketplace. I am unable to spend time supporting the [scan](https://github.com/ShiftLeftSecurity/sast-scan/) open-source project due to personal commitments. Since, the workflow is hard-coded your colleague suggested getting in touch via GitHub issues.

![Snag_1180d4c](https://user-images.githubusercontent.com/7842/140530951-bbcdf9a2-eff0-4ed1-86f6-a91a913d2edc.png)

Thank you for the opportunity and the support from your team, and thanks to the entire scan community for trusting my hobby project for your SAST and DevSecOps needs!

**Comment by nickfyson** [comment]
Hi @prabhu! I'm on the code scanning team, and apologies that we missed this issue at the time!

Would you still like your workflow removed from the set of starter workflows? If so, we've now moved all the workflows into this repo, so I'd be happy to approve a PR if needed!

Also, it's worth noting that the set of starter workflows (represented in this repo) is different to the github marketplace. The appearance of your action here...

https://github.com/marketplace/actions/security-and-licence-scan

...is distinct, and I think something that you can directly remove yourself.

**Comment by Phantsure** [comment]
This is deleted so closing this
