### ISSUE TITLE
About Qt enviornment?

### ISSUE THREAD

**Issue by lhy0403** [actions/starter-workflows#124]
Is there support of Qt env available?
I wanted to build my Qt c++ application in GithubAction but it's quite complicated to set up a Qt environment "by hand".

**Comment by andymckay** [comment]
If you question is how do I build with Qt? Then here's a few places that might help:

* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If you'd like submit a start workflow, please feel free to submit a pull request here, following these guidelines: https://github.com/actions/starter-workflows/blob/master/CONTRIBUTING.md

Thank you @lhy0403 🙇
