### ISSUE TITLE
Does it support ECS Blue/green Deployment?

### ISSUE THREAD

**Issue by wahackr** [actions/starter-workflows#1256]
I was try to migrate my Codepipeline to this GitHub Action for my ECS service with Blue/green deployment. I got the following message while the deployment is in the state of redirecting traffic from Original to Replacement. This process would turn succeed after 1 hour when I was using Codepipeline.

```
Deployment started. Watch this deployment's progress in the AWS CodeDeploy console: https://console.aws.amazon.com/codesuite/codedeploy/deployments/d-XXXXXXXX?region=us-east-1
Error: Resource is not in the state deploymentSuccessful
```

**Comment by SdRbrbd** [comment]
#يفان
![temp_file](https://user-images.githubusercontent.com/94808225/142782209-f657c06a-f87f-43f6-8a14-33d74eb4c5ad.jpeg)

**Comment by SdRbrbd** [comment]
I.V
