### ISSUE TITLE
how to pass username and password to twine for python-publish.yml

### ISSUE THREAD

**Issue by mikkokotila** [actions/starter-workflows#127]
@montudor it's not clear where `secrets` is coming from. Can you clarify.

```
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
```

**Comment by montudor** [comment]
Please refer to the actions documentation. [Secrets](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables) allow you to use sensitive information in your workflow without exposing the values publicly.

**Comment by mscoutermarsh** [comment]
Thinking you're all set here. Closing 😀

**Comment by webknjaz** [comment]
@mikkokotila FTR there's a guide at the Python Packaging Authority website that features a GitHub Action solely designed to follow the best publishing practices: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/.

@mscoutermarsh The current publishing template promotes bad practices (from the experienced Python dev and packager perspective) how open are you to accepting PRs for improving this?

**Comment by montudor** [comment]
@webknjaz I don't think you can claim it "promotes bad practices" when it follows the [packaging documentation](https://packaging.python.org/tutorials/packaging-projects/) which most users are going to be following. Perhaps this page should be updated in that case?

As for tokens, I can see their benefit, though, as stated in #69, the username and password fields were set as secrets in order to provide the user with the flexibility to choose whether to use tokens or not. The user merely needs to set their username secret as `__token__` to do so.

**Comment by webknjaz** [comment]
Right... Unfortunately, some of the practices still remain in the form of a "tribe knowledge", shared among the chosen ones in random places (confs/twitter/gh). That's being slowly improved over time as PyPA folks argue about the way of delivering this info in the best way newbies could understand.

**Comment by mscoutermarsh** [comment]
We're absolutely open to improving the workflow.

I personally haven't published a Python package before. Any best practices you all can share will be much appreciated. I can pull in some GitHub employees with Python experience to review.

**Comment by philnagel** [comment]
> Please refer to the actions documentation. [Secrets](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables) allow you to use sensitive information in your workflow without exposing the values publicly.

@montudor It seems that section has been dropped from that article, and the [article linked from it](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables) also makes no mention of how to specify the secret environment variables. Is there an updated URL available?

**Comment by montudor** [comment]
@philnagel Sorry about that, here is the [updated link](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

**Comment by emmamartins** [comment]
This will help to create a secret variables [https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)
