### ISSUE TITLE
publish-gpr: registry-url not set

### ISSUE THREAD

**Issue by denlb** [actions/starter-workflows#135]
[npmpublish.yml](https://github.com/denlb/timer-state-machine/blob/master/.github/workflows/npmpublish.yml#L43)

https://github.com/denlb/timer-state-machine/runs/228613882
```
npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/timer-state-machine - You must be logged in to publish packages.
```
Any hints what am I doing wrong? Seems like the `registry-url` was not set to https://npm.pkg.github.com/

**Comment by okuryu** [comment]
see https://github.com/actions/setup-node/issues/53

**Comment by denlb** [comment]
Not relevant to me anymore
