### ISSUE TITLE
Workflow stuck 95h

### ISSUE THREAD

**Issue by drodriguezhdez** [actions/starter-workflows#140]
![image](https://user-images.githubusercontent.com/29516565/65406927-38182f80-dde1-11e9-8901-8c6e81b214db.png)

The same workflow in a previous execution:

![image](https://user-images.githubusercontent.com/29516565/65406964-53833a80-dde1-11e9-995d-5d1244c56341.png)

The only change between both executions is the addition of the LICENSE file.

I don't know how to provide an ID of those jobs. I cannot locate it in the logs. :-(
Is there any place where I can find the jobs ID to provide them and give you more context info?

Thanks!!

**Comment by andymckay** [comment]
Sorry you are having that problem @drodriguezhdez , but we'd like to keep issues related to code in this repository.

* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

It sounds like in this case you should contact customer support. Thank you 🙇
