### ISSUE TITLE
actions how to support Third party CI tool(such as sonar)

### ISSUE THREAD

**Issue by freeeyes** [actions/starter-workflows#142]
I used travis CI.
such as this code:
    addons:
      sonarcloud:
        organization: "freeeyes-github"
        token:
          secure: "XXXXX"
Actions support does not support such syntax?
Integrate third-party CI detection tools to provide tokens for third-party tools？
thinks.

**Comment by andymckay** [comment]
Actions could work with third party tools, but any workflows added to this repository would need to match the contributor guidelines: https://github.com/actions/starter-workflows/blob/master/CONTRIBUTING.md

We'd like to keep issues related to code in this repository:

* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)
