### ISSUE TITLE
How to switch the context of command execution

### ISSUE THREAD

**Issue by GitHub-Pan** [actions/starter-workflows#143]
Hello, I am trying to use the github action to build the docker image and push it to dockerhub. But I have encountered a problem and don't know how to solve it. You know that xx.yml is under .github/workflows/, and my source code is at the same level as the .github folder. So I want to know how to switch context to my source code location.
Please help me thanks.

**Comment by GitHub-Pan** [comment]
I have solved this problem by add
`workworking-directory: ./`

**Comment by GitHub-Pan** [comment]
I have solved this problem by add 
working-directory: ./
It says your current repository is the context in which the command is executed.

**Comment by GitHub-Pan** [comment]
This answer may not be correct. I am still troubleshooting the specific reasons. Maybe the official can provide some suggestions.

**Comment by andymckay** [comment]
Thank you @GitHub-Pan, but we'd like to keep issues related to code in this repository.

* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)
