### ISSUE TITLE
Error handling in Actions

### ISSUE THREAD

**Issue by Ehsaan-Azizi** [actions/starter-workflows#1451]
I am running this workflow and in actions logs it shows error but the workflow finishes as completed (green check mark) anyway. Is there a way we can set up an error handling syntax within actions workflow yaml file where when there is an error and it should cancel the job? Please see below image.
![image](https://user-images.githubusercontent.com/84747162/155803287-d3df14d6-beaf-48f4-b016-f79078cd838b.png)

**Comment by Phantsure** [comment]
Stopping happens if the action throws an error. If it simply prints the error, then runner assumes it as info logging.

**Comment by Phantsure** [comment]
Does that answer your question? If you want to raise it further you may go to the respective actions repo where you encountered this issue and raise issue there.

**Comment by Phantsure** [comment]
@Ehsaan-Azizi Closing this for now. You may re-open this if any other questions arise. Thanks :)
