### ISSUE TITLE
Animated gradient border uses 30% CPU

### ISSUE THREAD

**Issue by maheshbalakrishnan** [actions/starter-workflows#147]
The animated gradient border on the 'New Workflow' page consistently takes up about 30% of my intel i7. Does this animation signify any background process that is running?

Here's what I am talking about
![image](https://user-images.githubusercontent.com/38936036/65669445-6de33100-dff8-11e9-8490-5de2d006cc9a.png)

`<div class=" .... anim-rainbow">`
`animation: MakeItRainbow ....`

Also hiding the `div` reduces the CPU usage.

**Comment by peaceiris** [comment]
You should report that at [GitHub Actions - GitHub Community Forum](https://github.community/t5/GitHub-Actions/bd-p/actions)

**Comment by maheshbalakrishnan** [comment]
Thanks, I will report it there!
