### ISSUE TITLE
QUESTION: How to bypass a failing step

### ISSUE THREAD

**Issue by pascalandy** [actions/starter-workflows#148]
Some steps are not critical. Is there a way for a step to fail but to continue the CI process?

Thanks!

**Comment by peaceiris** [comment]
[Contexts and expression syntax for GitHub Actions - GitHub Help](https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions#job-status-check-functions)

```yaml
if: always()
```

**Comment by pascalandy** [comment]
Thank you!!

**Comment by pascalandy** [comment]
Thanks, that should fix it :)
