### ISSUE TITLE
BUG: Still stuck on HCL syntax UI

### ISSUE THREAD

**Issue by DrSensor** [actions/starter-workflows#149]
I've push my first workflow here https://github.com/DrSensor/scdlang-vscode/commit/db9ea46446ffc9a51656244ee7f26c6cfd1470be

but when I click **Actions** tab,  I got this view
![image](https://user-images.githubusercontent.com/4953069/65767894-83bc3780-e159-11e9-9bda-c2bc4229b383.png)

Seems like it's the previous UI before github action adopt YAML syntax :thinking:

**Comment by mscoutermarsh** [comment]
@DrSensor Try now. your account is now set to the new YML for all repos.
