### ISSUE TITLE
Github Registry: where to ask

### ISSUE THREAD

**Issue by pascalandy** [actions/starter-workflows#150]
Where should I open bugs/questions about GPR. 

Thanks!
Pascal

**Comment by linuxjuggler** [comment]
@pascalandy mostly on the [community forum](https://github.community/t5/How-to-use-Git-and-GitHub/bd-p/Board_1) (I guess)

**Comment by mscoutermarsh** [comment]
Anything you submit via https://support.github.com/contact will make it to the team.

A section for GPR will be added to the community forum as well. Thanks!
