### ISSUE TITLE
Add GITHUB_TOKEN permissions for Datadog synthetics starter workflow

### ISSUE THREAD

**Issue by bishal-pdMSFT** [actions/starter-workflows#1504]
Each workflow needs to be define an appropriate least required permission for GITHUB_TOKEN. This ensures that the workflow is pre-authorized only for specific scopes and hence builds a more secure supply chain.

**Comment by Phantsure** [comment]
```
permissions:
  contents: read
``` 

this permission is required

**Comment by Deedsdirty** [comment]
No
