### ISSUE TITLE
docker/build-push-action needs to be updated in docker-publish.yml

### ISSUE THREAD

**Issue by bradbeck** [actions/starter-workflows#1519]
[docker-publish.yml](https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml) currently uses a version of `build-push-action` (`docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc`) that produces an incorrect digest (https://github.com/docker/build-push-action/pull/569) which results in the inability to verify signed images with `cosign`.

Updating to a more recent version e.g. `docker/build-push-action@v2` appears to resolve the issue.

**Comment by Phantsure** [comment]
Thank you for bringing this here. I hope someone can raise a PR for same.
