### ISSUE TITLE
My repo was built successfully, but badge always shows failing.

### ISSUE THREAD

**Issue by timandy** [actions/starter-workflows#1525]
The repo's default branch is `main`

repo: https://github.com/timandy/routine

badge:  https://github.com/timandy/routine/actions/workflows/build.yml/badge.svg

**Comment by polymonster** [comment]
I have the same problem, last failure was 5 days ago. Badge is still stuck on failing even though there have been multiple successful builds since.

https://github.com/polymonster/hotline/actions/workflows/samples.yaml
https://github.com/polymonster/hotline/actions/workflows/samples.yaml/badge.svg

**Comment by polymonster** [comment]
I was able to fix mine by deleting the old workflow runs that had failed.

**Comment by timandy** [comment]
@polymonster It looks all right now, thks for sharing your solution.

**Comment by scott-weeden** [comment]
I hate it when people close issues even though they're clearly still open.  Not even a reason as to why the issue was closed.

I can report the same bug is happening across github enterprise accounts and its widespread.  Nobody can report the bug though because github blocks enterprise accounts from reporting bugs.

**Comment by scott-weeden** [comment]
![image](https://user-images.githubusercontent.com/63826817/203600574-854690d0-28c5-4c64-9059-d425adb12e58.png)

Here's a screenshot of the badge and url.  Below is a screenshot of the success status on the job.  The github badge does not work

**Comment by sondalex** [comment]
Hi @ScottBrenner, if you replace `repository` query parameter by `branch` query parameter it should normally work. See GitHub documentation [adding-a-workflow-status-badge](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge).


To complete the doc:

```
[![A label](https://github.com/<author>/<repo>/actions/workflows/<workflow.yaml>/badge.svg?branch=<your branch>)](https://github.com/<author>/<repo>/actions/workflows/<workflow.yaml>)
```

**Comment by PapaPeskwo** [comment]
i have it pointint to my master branch, and not repo yet it still shows failing...

**Comment by PapaPeskwo** [comment]
hmm removed the branch extension in the url and it works... for now

**Comment by GodVenn** [comment]
Having the same issue. Doesn't work with or without pointing to branch.
But it does for some reason work if I set branch query parameter to blank `?branch=`

**Comment by SlimBenAmor** [comment]
According to this [documentation](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge), adding `?event=pull_request` parameter to the URL may solve the problem.

**Comment by petertwise** [comment]
Changing from using the "name" parameter to the filename worked for me.

Used to work, but now always shows failing:
https://github.com/username/reponame/actions/workflows/WordPress%20Standards/badge.svg?branch=develop

This one works as expected:
https://github.com/username/reponame/actions/workflows/wpstandards.yml/badge.svg?branch=develop

This is probably because we used to use a different .yml filename... changing the filename but using the same `name` parameter does not seem to work.

**Comment by kmturley** [comment]
I was using the old format 
`/workflows/WORKFLOW_NAME`

Docs say to use a new format:
`/actions/workflows/WORKFLOW_FILENAME.yml`

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

So I changed from:
https://github.com/kmturley/sfz-tools-core/workflows/Test/badge.svg

To:
https://github.com/kmturley/sfz-tools-core/actions/workflows/test.yml/badge.svg

and it works!

**Comment by romdj** [comment]
Had the same issue, but be sure to clear your cache when checking the badge

**Comment by rogueloop** [comment]
Still not fixed for me

**Comment by spuder** [comment]
I'm also running into this. 
I've verified I'm using `.yaml` and not `.yml` for the file name. 
I've copied/pasted other working badges and replaced it with my correct owner/repo. 

Nothing worked. 

## Workaround
 Just rename `workflows/build.yaml` to something new like `workflows/foobar.yaml`. 
 
 ![](https://github.com/spuder/openspool/actions/workflows/esphome.yaml/badge.svg)

**Comment by cloverink** [comment]
Same issue and same solution lol. Leave it blank
`https://github.com/xxx/yyy/actions/workflows/zzz.yml/badge.svg?branch=`
