### ISSUE TITLE
Action workflow build successful, but badge displays `no status`

### ISSUE THREAD

**Issue by epomatti** [actions/starter-workflows#1526]
All my actions builds are green:

https://github.com/epomatti/wsl2-dns-fix-config/actions/workflows/shell.yml

But my Badge displays `no status`:

https://github.com/epomatti/wsl2-dns-fix-config/actions/workflows/shell.yml/badge.svg

**Comment by vroncevic** [comment]
@epomatti did You try to delete workflow runs with [GitHub CLI](https://cli.github.com/) ?

**Comment by epomatti** [comment]
I deleted the GH badge in favor of shields.io one, that worked so I'm fine with it for now.
