### ISSUE TITLE
starter workflow for the meson build system

### ISSUE THREAD

**Issue by andy5995** [actions/starter-workflows#1532]
I'd consider giving the option of `meson` as well since it seems the current migration path from autotools for many big projects.

_Originally posted by @lu-zero in https://github.com/actions/starter-workflows/issues/53#issuecomment-523868893_

@mesonbuild

**Comment by andy5995** [comment]
@Phantsure I think I could handle this ticket if you wanna reassign it.

**Comment by Phantsure** [comment]
Sure you can work on this ticket.

**Comment by Phantsure** [comment]
@andy5995 Sorry I didn't realise this is CI template request. We are currently not taking those for now. Closing this issue to avoid confusion.
