### ISSUE TITLE
version tags or bare numbers

### ISSUE THREAD

**Issue by pinohcarlos** [actions/starter-workflows#1547]
@imjohnbo @craigdbarber Thanks! For what it's worth, most of our actions have tags that are prefixed with `v`, e.g. `v0`, `v0.2.0`. I think this is just a convention though, if you prefer to stick with bare version numbers.

_Originally posted by @hashtagchris in https://github.com/actions/starter-workflows/issues/241#issuecomment-561672647_

**Comment by Phantsure** [comment]
@pinohcarlos We prefer release tags with `v` or commit SHA of release. It is recommended to use commit SHA for third party actions

**Comment by Phantsure** [comment]
Is there anything else you would like to clarify?

**Comment by Phantsure** [comment]
@pinohcarlos Closing this issue for now. Re-open this if you have any other questions. Thanks :)
