### ISSUE TITLE
Missing + duplicate starter action on the actions setup page

### ISSUE THREAD

**Issue by montudor** [actions/starter-workflows#155]
On the get started with actions screen while setting up Actions for a project, the [Python package](https://github.com/actions/starter-workflows/blob/master/ci/python-package.yml) template is displayed twice in the list, while the [Publish Python Package](https://github.com/actions/starter-workflows/blob/master/ci/python-publish.yml) template (#69) is not displayed at all.

**Comment by andymckay** [comment]
Thanks for the heads up @montudor, we'll get that to show up.

**Comment by andymckay** [comment]
It's showing up now, yay!

<img width="419" alt="Screen Shot 2019-10-16 at 2 55 46 PM" src="https://user-images.githubusercontent.com/74699/66962104-0f243c80-f025-11e9-99cb-69e6c53a79cd.png">

**Comment by montudor** [comment]
Great! Thanks @andymckay!
