### ISSUE TITLE
<!-- MODIFIED_CONTENT_LINKING_COMMENT --> https://github.com/github/docs/pull/17510#issuecomment-1114107149_

### ISSUE THREAD

**Issue by farahmandakbar** [actions/starter-workflows#1553]
## Automatically generated comment ℹ️
**This comment is automatically generated and will be overwritten every time changes are committed to this branch.**

The table contains an overview of files in the `content` directory that have been changed in this pull request. It's provided to make it easy to review your changes on the staging site. Please note that changes to the `data` directory will not show up in this table.

---

### Content directory changes
_You may find it useful to copy this table into the pull request summary. There you can edit it to share links to important articles or changes and to give a high-level overview of how the changes in your pull request support the overall goals of the pull request._
| **Source** | **Preview** | **Production** | **What Changed** |
|:----------- |:----------- |:----------- |:----------- |
| [content/get-started/quickstart/fork-a-repo.md](https://github.com/github/docs/blob/c6d3507b88131b8fa00b356245692d0642a64f1b/content%2Fget-started%2Fquickstart%2Ffork-a-repo.md) | [Modified](https://docs-17510-3808bd.preview.ghdocs.com/get-started/quickstart/fork-a-repo) | [Original](https://docs.github.com/get-started/quickstart/fork-a-repo) | |

_Originally posted by @github-actions in https://github.com/github/docs/pull/17510#issuecomment-1114107149_

**Comment by Phantsure** [comment]
@farahmandakbar Can you provide more context on this issue and reopen this? Thanks.
