### ISSUE TITLE
learn-github-actions.yml

### ISSUE THREAD

**Issue by Audy93** [actions/starter-workflows#1565]
name: learn-github-actions

**Comment by Audy93** [comment]
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

**Comment by Phantsure** [comment]
@Audy93 Can you provide the rationale behind this issue? Thanks

**Comment by Audy93** [comment]
My bad I'm trying hard to understand how to creat a branch and how to do request a new GitHub workf by following some example.

**Comment by Audy93** [comment]
I messed up

**Comment by Phantsure** [comment]
@Audy93 Try this to create a branch.  https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository
Note: you might be able to fork this repository to experiment as much as you like.

For workflows, head over to `Actions` tab and try creating a new workflow. You may start with a simple workflow.
