### ISSUE TITLE
Use `jobs.<job_id>.needs` field to depend on workflow from another yml config

### ISSUE THREAD

**Issue by aamorozov** [actions/starter-workflows#157]
Our use case requires us to have multiple yml file to split the deployments of our services and we're trying to setup the workflow in one file to depend on a successful completion of another workflow but not able to. Is it something that is currently not supported? Essentially, I think it comes down to being able to add dependencies between workflows and trigger one based on a success/cancel on failure of another.

**Comment by deitch** [comment]
Yes, quite. This solves a very common use case: CI and CD. I might run my build (+test, etc.) in one workflow that applies to every change/PR/etc., while CD (or even just pushing an image or compiled artifact out, which arguably is within the CD realm, maybe...) happens only on pushes (or completed merges, same thing) into `master`. 

I don't want to redefine the entire build process from the CI workflow file in the CD workflow. That is DRY and begging for errors in the future. I want to have a CI workflow that always runs, and a CD workflow that sometimes runs, but _after_ my CI workflow.

**Comment by deitch** [comment]
FYI, I would be happy with a workflow-level `needs:` that points to another workflow. That plus `on:` conditions would make it work nicely.

**Comment by andymckay** [comment]
Thank you 🙇 for creating the issue in this repository, but we are trying to keep issues related to the code in this repo.

* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)
