### ISSUE TITLE
default haskell workflow doesn't find cabal

### ISSUE THREAD

**Issue by mjhoy** [actions/starter-workflows#159]
The result of using the default haskell workflow gives me `cabal: command not found` in the "Install dependencies" phase. Example: https://github.com/mjhoy/mikey.bike/commit/986fefe08f00b140037a92cbfdb40a7b2d8e5714/checks?check_suite_id=247322881

**Comment by peaceiris** [comment]
FYI [actions/setup-haskell](https://github.com/actions/setup-haskell).

**Comment by mjhoy** [comment]
ah, thanks!

does it make sense for the default to reference this? i'm just getting starting with actions, and this was a bit confusing.

**Comment by peaceiris** [comment]
I think that the default workflow should use the official setup action. The action is new, so the starter workflow hasn't been updated yet. You can create your Pull Request and update the Haskell default workflow for the Haskell community.

**Comment by andymckay** [comment]
Thank you @mjhoy, with the merge of #160 this should now be fixed. If its not please let us know.
