### ISSUE TITLE
https://github.com/facebookarchive/?fbclid=IwAR1sE69tJq8QvQp1NDx1aEWDuG8SPIsCrSAuCD7j3PiL8sv3wBnpls7nS2Y

### ISSUE THREAD

**Issue by victorinojeffrey92** [actions/starter-workflows#1606]
https://research.facebook.com/blog/2017/6/facebook-disaster-maps-methodology/

**Comment by Phantsure** [comment]
@victorinojeffrey92 Can you please add more context around the issue and re-open this one?
