### ISSUE TITLE
docker-publish.yml cosign sign fails for docker images with multiple tags due to spanning multiple lines

### ISSUE THREAD

**Issue by jamesmoore** [actions/starter-workflows#1620]
https://github.com/actions/starter-workflows/blob/692c4c52607f67dd3ee34ad0b7c26066ae85bbae/ci/docker-publish.yml#L93

I think there could be a problem with this line where the tags contain multiple entries. 

# Failure case:

This action is a near vanilla docker-publish.yml (only `workflow_dispatch` added) and the run triggered by the scheduled cron which generates `nightly ` and `master` tags:

https://github.com/jamesmoore/SPFtoolbox/runs/7042708301?check_suite_focus=true#step:8:2

It appears that the second tag is output on the following line and the shell attempts to execute it as a command.

# Success case:

The same workflow run with `workflow_dispatch` or a push then the command the action succeeds. In this case there is only one tag which is the branch name.

Eg, https://github.com/jamesmoore/SPFtoolbox/runs/7053298880?check_suite_focus=true#step:8:2

**Comment by jamesmoore** [comment]
Prospective fix here: https://github.com/actions/starter-workflows/pull/1622

**Comment by Phantsure** [comment]
Merged the PR associated. Closing this issue with that
