### ISSUE TITLE
How to prevent individuals or a team to edit GitHub actions based workflow of a particular repository?

### ISSUE THREAD

**Issue by msrinivascharan** [actions/starter-workflows#1628]
I have a GiHub repository with GitHub actions based workflow (/.github/workflows/build.yml) to do CI builds.

I am from the DevOps team, my case, folks from development team are not allowed to change CI pipelines, they can change whatever they want on a feature branch except “/.github/workflows/build.yml”.

How to prevent a developer changing GitHib workflow to see his app changes passing through different type of integration build quality checks ?

Is there any better approach to achieve this  other than options mentioned below ?

   1]  Through PR reviews
   2]  Script/automation to validate PR to see if dev did any changes to (/.github/workflows/build.yml

**Comment by nirmalank** [comment]
I am also struggling with the same issue and looking for better solution :)

**Comment by Phantsure** [comment]
> 2] Script/automation to validate PR to see if dev did any changes to (/.github/workflows/build.yml

Isn't second option good enough with a mandatory check? If the check fails, i.e. the developer has changed the file then don't allow merge.

**Comment by axmdki** [comment]
เช่นกัน ฉันพยายามค้นหาและดิ้นรนเพื่อที่จะแก้ไขปัญหาที่ แก้ไม่แล้วเสร็จตามที่คาดหมาย พอมีวิธีง่ายๆที่จะแนะนำบ้าง และโฟล์คการเชื่อมต่อไม่พบการสตริงค์ข้อมูลและไม่ตรงกับ โค๊ดที่ เวอร์ชั่นซีเรอรับ 
รบกวนแนะนำและสนับสนุน ด้วยความเต็มใจที่ได้รับความช่วยเหลือ 
ยินดีใจ ขอให้เป็นวันที่ดี

**Comment by JamesMGreene** [comment]
If you end up using an Actions workflow to verify this kind of a thing for a repository where changes are made via Pull Requests, definitely look into using the [`pull_request_target` trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) instead of `pull_request` as the former will utilize the copy of the workflow from the base branch instead of the PR's head branch.

That way, you can also rest assured that the workflow to verify things wasn't changed in the PR either. 😜

**Comment by discordianfish** [comment]
I think this is a very valid concern. The trigger can't help because the developer can change it.
An mandatory check can also be removed in the branch.

**Comment by Kampe** [comment]
I believe this needs a solution

**Comment by discordianfish** [comment]
fwiw, I've solved this by using:

1. reusable workflow in a separate repo which regular developers can't change
2. grant permissions (in our case pushing to ECR) via oidc claim based on job_workflow_ref, so that only actions using that reusable workflow can assume the role

**Comment by gilesbradshaw** [comment]
I made a pull_request_target workflow which fails if anything in the .github folder has changed.

```
---
name: pull-request-target

on:
  pull_request_target:
permissions:
  contents: read
  pull-requests: write
jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Example 3
      - name: Get all .github chnages
        id: changed-files-yaml
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            github:
              - .github/**

      - name: fail step if test file(s) change
        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files-yaml.outputs.test_any_changed == 'true'  
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('.github files chnaged')
      - uses: kentaro-m/auto-assign-action@v1.2.5

```

**Comment by rarescosma** [comment]
For other lost souls who end up here from their searches: https://github.com/orgs/community/discussions/27084#discussioncomment-3254544

Thus, this isn't really a concern.

**Comment by matejdro** [comment]
This only applies to the `pull_request_target` though. Other events, such as `workflow_dispatch` can still execute workfolow actions directly from branches.
