### ISSUE TITLE
Hugo starter workflow should be used in production mode

### ISSUE THREAD

**Issue by EricStG** [actions/starter-workflows#1683]
The Hugo workflow at /pages/hugo.yml produces a "development" mode, which leaves some things a robots.txt file that prevents crawling

```
User-agent: *
# robotstxt.org - if ENV production variable is false robots will be disallowed.

Disallow: /
```

To build Hugo pages in production mode, the environment variable `HUGO_ENV` should be set to `production` during the build

**Comment by JamesMGreene** [comment]
**Disclaimer:** I am not an avid Hugo user, so please enlighten me if I'm missing some background. 🙏🏻 

From what I've read, it appears that the preferred way to set this is via the `--environment` CLI flag: https://gohugo.io/functions/hugo/#prose

This will appropriately configure `hugo.Environment` and `hugo.IsProduction`, as well as [setting the environment variables `HUGO_ENV` and `HUGO_ENVIRONMENT`](https://github.com/gohugoio/hugo/blob/b017f7cb0136ee33f5d19749a15bf3365a991ac5/common/hugo/hugo.go#L124-L125).

> `hugo.Environment`
> the current running environment as defined through the `--environment` cli tag

One thing of interest is that I would've assumed that Hugo defaulted to a production build based on [this code](https://github.com/gohugoio/hugo/blob/b017f7cb0136ee33f5d19749a15bf3365a991ac5/common/hugo/hugo.go#L89-L91) but that would only apply if the environment isn't already set somewhere else.

Either way, setting it explicitly to production in our starter workflow seems like a valid idea to me. 👍🏻

**Comment by JamesMGreene** [comment]
Opened PR: https://github.com/actions/starter-workflows/pull/1689

**Comment by EricStG** [comment]
Not an expert either, but it seems that some modules/themes are a bit slow in supporting `--environment` (including the theme I'm using, unfortunately).
That being said, it probably makes sense in the this workflow to use that instead of the env var.

**Comment by JamesMGreene** [comment]
I am hopeful that the Hugo ecosystem at large is covered by the fact that it _appears_ Hugo will set the corresponding environment variables as well. 🤔 🤞🏻 

> This will appropriately configure `hugo.Environment` and `hugo.IsProduction`, as well as [setting the environment variables `HUGO_ENV` and `HUGO_ENVIRONMENT`](https://github.com/gohugoio/hugo/blob/b017f7cb0136ee33f5d19749a15bf3365a991ac5/common/hugo/hugo.go#L124-L125).

Hugo support:
- `HUGO_ENVIRONMENT` has been set [since version `v0.70.0`](https://github.com/gohugoio/hugo/commit/6add6d77b48cf0aab8b39d7a2bddedb1aa2a52b8)
- `HUGO_ENV` has been set [since version `v0.92.2`](https://github.com/gohugoio/hugo/commit/4f4cec73be40e7bd4cfcffb461e75e415db45821)

**Comment by JamesMGreene** [comment]
PR has been merged. 🚀

**Comment by EricStG** [comment]
@JamesMGreene Thanks!

What I encountered is the opposite. 
In some Hugo modules, instead of looking at `hugo.Environment` or `hugo.IsProduction`, they use `if eq (getenv "HUGO_ENV") "production" directly`

That being said, I don't know how common that is, maybe I just got unlucky

**Comment by JamesMGreene** [comment]
@EricStG Are you using a version of Hugo prior to `v0.92.2`? As far as I can tell, that version and newer should be handling the use case you've described by setting `HUGO_ENV` internally based on `hugo.Environment`. 🤔

**Comment by EricStG** [comment]
@JamesMGreene Sorry, I wasn't clear.
The problem I have is not the logic used by Hugo itself, but 3rd party modules using the env var directly.

**Comment by JamesMGreene** [comment]
@EricStG My apologies, you were clear enough the first time. My mistake was in assuming that Hugo's `SetEnvVars` calls were actually invoking [`os.Setenv`](https://pkg.go.dev/os#Setenv) or something similarly official that would affect the execution environment for Hugo modules -- but apparently they are not. 😅 

Now that I've looked through Hugo's source more, it appears those `SetEnvVars` calls are only setting up some strings in the `KEY=value` command-line style for the [`GetExecEnviron` function](https://github.com/gohugoio/hugo/blob/b017f7cb0136ee33f5d19749a15bf3365a991ac5/common/hugo/hugo.go#L116), which are later [passed into `babel`](https://github.com/gohugoio/hugo/blob/b017f7cb0136ee33f5d19749a15bf3365a991ac5/resources/resource_transformers/babel/babel.go#L174) and [passed into `postcss`](https://github.com/gohugoio/hugo/blob/b017f7cb0136ee33f5d19749a15bf3365a991ac5/resources/resource_transformers/postcss/postcss.go#L203). As such, this presumably only affects asset transpiling but potentially fails to cover Hugo modules that access `HUGO_ENV`/`HUGO_ENVIRONMENT` in their Go code.

I've talked through it with my team, and we agree that setting those environment variables (and _not_ setting the command line `--environment` flag) probably make the most sense for maximum compatibility. 👍🏻 

Another PR is forthcoming. :eyes:

**Comment by JamesMGreene** [comment]
New PR: https://github.com/actions/starter-workflows/pull/1696

Does that look like it will better suit your needs, @EricStG? 😅 🤞🏻

**Comment by EricStG** [comment]
@JamesMGreene Looks good to me!

**Comment by JamesMGreene** [comment]
_That_ PR has now been merged. 😅 🚀 

Thanks for your patience and perseverance in explaining this issue to us! 💝 ✨
