### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by liwson** [actions/starter-workflows#1717]

**Comment by chonthichayaver** [comment]
Okay,. So please remind him don't be late than 17.00  because i confirm
nurse now i will pay right here in hour for sure.

PS.  PLEASE TRY TO RECOMINDED  CAN NOT LATE THAN 17.00.  SERIOUSLY



ในวันที่ อา. 28 ส.ค. 2022 16:06 น. liwson ***@***.***>
เขียนว่า:
