### ISSUE TITLE
[Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by fromxt** [actions/starter-workflows#174]
Hi there
I setup a Python package workflow and have following error : 

`pip install -r requirements.txt [Errno 2] No such file or directory: 'requirements.txt'`

I don't know  where requirements.txt is located. But just replace `pip install -r requirements.txt` with `pip freeze > requirements.txt` command in line 23 ` starter-workflows/ci/python-package.yml`. It works.

**Comment by nullforce** [comment]
You would need to check in your `requirements.txt` with your code. Otherwise the CI server would not know what requirements need to be installed to build your code.

**Comment by fromxt** [comment]
Oh~ Thank you!
