### ISSUE TITLE
Expand-Archive : is not a supported archive file format. .zip is the only supported archive file format | Kong Insomnia | Self Hosted Runner | Windows

### ISSUE THREAD

**Issue by KKiruthika10** [actions/starter-workflows#1743]
Below is the snippet from the workflow action yml file in git:

jobs:
  Linux:
    name: Validate 
    runs-on: self-hosted
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Lint
        run: inso lint spec "Designer Demo" --ci

Getting the below exception in Run kong/setup-inso@V1 step while executing the github action workflow:

Installing inso version 2.4.0-windows
..
Expand-Archive : is not a supported archive file format. .zip is the only supported archive file format 

The subsequent job Lint fails with the below error:

inso : The term 'inso' is not recognized as the name of a cmdlet, function, script file, or operable program

**Comment by Phantsure** [comment]
@KKiruthika10 Is this is right place to put this question?

**Comment by Phantsure** [comment]
@KKiruthika10 Closing this due to no response
