### ISSUE TITLE
Missing Link from python-package.yml

### ISSUE THREAD

**Issue by John-Poulos** [actions/starter-workflows#1754]
Line #2 in python-package.yml at https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml
appears to be a dead link. It will bring up the generic support page (https://support.github.com/) instead.

From yaml: 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

**Comment by chabala** [comment]
Indeed, all the deeplinks in comments seem to be broken, e.g. in `maven.yml` https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven also redirects to the generic support page.
