### ISSUE TITLE
Feat: Starter workflow for Flutter Web

### ISSUE THREAD

**Issue by fkromer** [actions/starter-workflows#1776]
Would be great to have some [starter workflow for pages](https://github.com/actions/starter-workflows/tree/main/pages) build with Flutter for web. Would allow to prevent a lot of [Invalid actions OIDC token issue](https://github.com/actions/deploy-pages/issues/9) feedback probably.

**Comment by JamesMGreene** [comment]
Our general stance so far has been to only offer official Pages starter workflows for static site generators versus more open-ended web application frameworks like Flutter.

@yoannchaudet Thoughts?

**Comment by yoannchaudet** [comment]
@JamesMGreene Agreed.

@fkromer Not having a starter workflow does not mean it is not supported but just that it is an unusual scenario without a lot of demand that we don't want to highlight in this repository. 

We try hard to curate what we expose as starter workflows and there is a lot of hidden work that goes into it (non-regression tests, vendoring for GitHub Enterprise Server, stack suggestions/detections).

**Comment by fkromer** [comment]
@yoannchaudet Sounds reasonable. Just wanted to indicate that some folks are already using Flutter in the web as well already.
