### ISSUE TITLE
Unable to successfully build and test Hello World iOS app with iOS starter workflow

### ISSUE THREAD

**Issue by mvescovo** [actions/starter-workflows#1781]
Hi. So far I've not been able to successfully build and test a Hello World iOS app with iOS starter workflow.

I posted in the discussion forum here https://github.com/orgs/community/discussions/35585 but didn't get any responses. I'm wondering if maybe the workflow on this repository where I'm posting the issue has become out of date and is missing a step or something?

---

I created a hello world app here https://github.com/mvescovo/test_ios_workflow and added the iOS starter workflow but I get this error:

```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[19](https://github.com/mvescovo/test_ios_workflow/actions/runs/3213713817/jobs/5253588149#step:4:20)
		{ platform:iOS Simulator, OS:latest, name:iPhone 11 }
[20](https://github.com/mvescovo/test_ios_workflow/actions/runs/3213713817/jobs/5253588149#step:4:21)

[21](https://github.com/mvescovo/test_ios_workflow/actions/runs/3213713817/jobs/5253588149#step:4:22)
	Ineligible destinations for the "test_ios_workflow" scheme:
[22](https://github.com/mvescovo/test_ios_workflow/actions/runs/3213713817/jobs/5253588149#step:4:23)
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[23](https://github.com/mvescovo/test_ios_workflow/actions/runs/3213713817/jobs/5253588149#step:4:24)
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
[24](https://github.com/mvescovo/test_ios_workflow/actions/runs/3213713817/jobs/5253588149#step:4:25)
Error: Process completed with exit code 70.
```

Any help appreciated. Thanks :)

p.s. I did the same thing on Android and it worked without having to do anything else. No errors.

**Comment by mvescovo** [comment]
Ok I got it to work by changing the iOS version to 15.0. I previously had it on 16.0. Seem that version is not supported yet on Github Actions; it works fine from Xcode with the same command.

**Comment by Phantsure** [comment]
@mvescovo Do you think we require any change in starter-workflow to address that?

**Comment by mvescovo** [comment]
@Phantsure I'm not familiar enough with iOS builds to answer that. If not you can close this issue. Also, do you know who could address that? Thanks.

**Comment by Phantsure** [comment]
I am not familiar with IOS development so don't really understand the issue. But because it seems resolved we should be able to close it safely

**Comment by mvescovo** [comment]
It's not resolved as far as I know but I've moved on and using Xcode cloud instead which works fine on iOS16. So it seems the solution is to just not use Github actions for iOS if you want to target iOS16. Given that, I don't mind that you closed it.
