### ISSUE TITLE
This is a duplicate of #1525

### ISSUE THREAD

**Issue by scott-weeden** [actions/starter-workflows#1835]
When a GitHub workflow action (running on windows 2019) completes successfully .... zero errors (not even a continue on error) 

l... the badge continues to show as failing.
![image](https://user-images.githubusercontent.com/63826817/203601740-a7c156d1-1bd3-4aac-af21-d68e0e02fbd5.png)

**Comment by Phantsure** [comment]
I think this is not the right place for this question. Is the workflow taken from here?

**Comment by Phantsure** [comment]
@scott-weeden Closing this as this doesn't feel to be the right place for this
