### ISSUE TITLE
Use cache in CI workflows

### ISSUE THREAD

**Issue by thisismydesign** [actions/starter-workflows#188]
Hey,

It would be awesome if the starter workflows would use the new [cache](https://github.com/actions/cache) feature out of the box.

**Comment by thisismydesign** [comment]
Still relevant

**Comment by thisismydesign** [comment]
Still relevant

**Comment by thisismydesign** [comment]
Still relevant

**Comment by AverageComet250** [comment]
Wow will this even be looked at?

It seems to just be you and the issue bot just closing it and opening it

**Comment by thisismydesign** [comment]
Don't close this issue. This is an automatic message by [Fresh](https://github.com/c-hive/fresh) - a bot against stale bots.

**Comment by thisismydesign** [comment]
Still relevant

**Comment by thisismydesign** [comment]
Don't close this issue. This is an automatic message by [Fresh](https://github.com/c-hive/fresh) - a bot against stale bots.

**Comment by thisismydesign** [comment]
Hey bot, why not keep it around

**Comment by natthapon8517** [comment]
74d0be618be926dd

**Comment by natthapon8517** [comment]
ยกเลิกการปฏิเสธ
