### ISSUE TITLE
> I was running into the same issue, @ericsciple thanks for the workaround suggestion! :)

### ISSUE THREAD

**Issue by jbaryy708** [actions/starter-workflows#1923]
> I was running into the same issue, @ericsciple thanks for the workaround suggestion! :)
> 
> do you know if the `$GITHUB_WORKSPACE` variable can be changed elsewhere?

Can you  help me?

_Originally posted by @jbaryy708 in https://github.com/actions/checkout/issues/197#issuecomment-1410956092_

**Comment by Phantsure** [comment]
`$GITHUB_WORKSPACE` is the location for workspace where runner is executing commands. It can't be modified as per my understanding
