### ISSUE TITLE
How are magic variables like: `$detected-codeql-languages` set?

### ISSUE THREAD

**Issue by jessehouwing** [actions/starter-workflows#1926]
How are magic variables like: `$detected-codeql-languages` set? Is this something only GitHub can change? Or is this something we can provide through a PR for our own template-action-workflows as well?

**Comment by chuckbartz2666** [comment]
Uploading cards automatically and read accounts on the cards

**Comment by chuckbartz2666** [comment]
Sleeping code

**Comment by chuckbartz2666** [comment]
#1934

**Comment by chuckbartz2666** [comment]
Duplicate of #645

**Comment by chuckbartz2666** [comment]
> `[PayPal ](https://PayPal.com) `

**Comment by chuckbartz2666** [comment]
Trick system

**Comment by Phantsure** [comment]
In example of https://github.com/actions/starter-workflows/blob/main/code-scanning/codeql.yml#L35 , it is a subset of [languages present in repo](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-languages) which are [supported by codeql](https://aka.ms/codeql-docs/language-support).

You can set custom env variables variables for workflows: https://docs.github.com/en/actions/learn-github-actions/variables

**Comment by jessehouwing** [comment]
I know what variables are and what is done with these in the CodeQL workflow. But can I create a custom workflow template with a custom $owning-burinessline or anything else that will be automatically filled in when the workflow is created?

How is the actual value of $detected-lanquages set and can I provider a similar value provider for my own purpose?

**Comment by Phantsure** [comment]
Actual value of that variable is set internally. You can write a custom workflow to set value of repository environment variables according to external response: https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#update-a-repository-variable. You may use this API for this use case

**Comment by Phantsure** [comment]
No, you can't set internal variable. If you try to set, outcome won't be as expected
