### ISSUE TITLE
pages/static.yml: What does the "Setup Pages" step achieve?

### ISSUE THREAD

**Issue by andreasabel** [actions/starter-workflows#1996]
The workflow template to deploy a static web page contains an `actions/configure-pages` step:
https://github.com/actions/starter-workflows/blob/9e75fa6b3294adf3aa695272b2fbc6104ad75cba/pages/static.yml#L34-L35

Does this step achieve anything for static pages?
- If yes, please document why it is necessary or useful.
- If no, please remove.

**Comment by andreasabel** [comment]
It is not my fault that this issue has become stale.  I am still waiting for a response.

**Comment by yoannchaudet** [comment]
You can learn more about this step in https://github.com/actions/configure-pages#configure-pages.

It enable Pages if needed, extract metadata (e.g. the URL to access your Pages site) and does automatic configuration (related to base path) for some static site generators (nuxt, next, gatsby, sveltekit).

If we document it in the starter workflows, it means we believe it is useful for most people. It is open source and if you disagree with the usefulness of the step, don't hesitate to remove it from your own workflows.

**Comment by JamesMGreene** [comment]
It's fair to say that, in this case, it likely isn't doing anything for most folks with a static site. 🤔 

We've left it in as it is potentially still useful if you decide you want to expand what the starter workflow does once you've added it to your own repository. However, it might be reasonable to comment it out as a step and just leave a note about why you may want to use it. 🤷🏻 

Would be open to a PR to that effect, or, as Yoann mentioned, you can feel free to remove it from your own workflows as well. 👍🏻
