### ISSUE TITLE
Multi-container testing example

### ISSUE THREAD

**Issue by koenhoeijmakers** [actions/starter-workflows#20]
Would be nice to have an example of multi container testing as a starter workflow :)

This is hinted upon in the feature page but I've been looking through all the docs but could not find a single item about this.

**Comment by peter-evans** [comment]
Not sure if this is the kind of example you were looking for, but I just tested out a workflow using `docker-compose` here.
https://github.com/peter-evans/docker-compose-actions-workflow

This may not be suitable as a "starter workflow" because it needs too many other files to be present in the repository.

**Comment by koenhoeijmakers** [comment]
I've indeed gotten to building from `docker-compose` as in your repository and that might be a good starting point for many so thanks for linking @peter-evans !

But I have ran into some issues right now for which I have mailed GitHub, I'll report back when I have heard from them.

My current issues were 2 things:
1. I couldn't bind anything to port 3306 (MySQL).
2. I couldn't cache the containers (my containers take 10 minutes to build so that's not really pretty).

**Comment by peter-evans** [comment]
I'm interested to know further details when you hear back. I also have a similar situation that I've contacted support about with a `docker-compose` stack that doesn't seem to be behaving correctly. I suspect there are some networking or port binding issues at the moment.

**Comment by chrispat** [comment]
Here is an example using services in an actions workflow https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml.  Not sure this can really be a starter workflow.

**Comment by koenhoeijmakers** [comment]
@peter-evans it seems that there are indeed some kind of networking problems, my problem right now:
I have a container with the name `db` and a container with the name `app` but i can't connect to `db` from the `app` container, i can however use `docker exec` to get into 1 of the containers.

**Comment by chrispat** [comment]
https://github.com/actions/example-services has a couple of examples
