### ISSUE TITLE
dotnet-core.yml should use `dotnet test` if tests are to be run

### ISSUE THREAD

**Issue by lee-11** [actions/starter-workflows#208]
Looking at the `dotnet-core.yml` Activity, the description of it on the [listing page](https://github.com/eleven-software/portal-manager/actions/new) states that it "builds and tests" a .Net Core project. And that's the Right Thing, based on what the other listed Activities do.

However, in the repo the code only does a `dotnet build` which will not run tests.  The full command should instead be `dotnet test --configuration Release` which will build *and* test the project.  Small but important difference.

**Comment by phantommyk** [comment]
ad4g:master

**Comment by phantommyk** [comment]
Thanks for you partipation

**Comment by fedakova** [comment]
Já m,slin že to je rozumné
