### ISSUE TITLE
> Working cmake workflow:

### ISSUE THREAD

**Issue by erick-co** [actions/starter-workflows#209]
> Working cmake workflow:
> 
> ```
> name: C/C++ CI
> 
> on: [push]
> 
> jobs:
>   build-ubuntu:
> 
>     runs-on: ubuntu-latest
>     
>     steps:
>     - uses: actions/checkout@v1
>     - name: configure
>       run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
>     - name: build
>       run: cmake --build build
>     - name: test
>       run: cd build && ctest
> 
>   build-windows:
> 
>     runs-on: ${{ matrix.os }}
>     strategy:
>       matrix:
>         os: [windows-latest, windows-2016]
>     
>     steps:
>     - uses: actions/checkout@v1
>     - name: configure
>       run: mkdir build && cd build && cmake ..
>     - name: build
>       run: cmake --build build --config Debug
>     - name: test
>       run: cd build && ctest
> ```
> 
> _Originally posted by @rigtorp in [#53 (comment)](https://github.com/actions/starter-workflows/issues/53#issuecomment-537847198)_

_Originally posted by @erick-co in https://github.com/actions/starter-workflows/issues/196#issuecomment-555874921_

**Comment by zbeekman** [comment]
A few comments/suggestions:

- As a general comment, the current c/cpp workflow and this CMake workflow are not really specific to C/C++. For example, Fortran and a host of other compiled languages can use make/CMake/autotools
- This workflow could be improved by using CMake's shell/OS agnostic command line syntax for builds which can handle the creation of the build directory
  - This would enable a single job across all 3 OSes via a build matrix

**Comment by basavyr** [comment]
The configuration can also be improved by adding the build artifacts, which contains the executable(s) of the respective project. 

Nevertheless, this is a very useful configuration example, which helped me a lot in setting up my pipeline. Thank you!
