### ISSUE TITLE
$default-branch expands to name in double quotes

### ISSUE THREAD

**Issue by abitrolly** [actions/starter-workflows#2100]
> If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

[`$default-branch`](https://github.com/actions/starter-workflows/blob/0582bb6eb45cd5c60bcb0ce2a35fe50bbc0c2c0d/README.md?plain=1#L50) expands to name in double quotes that [are invalid](https://docs.github.com/en/actions/learn-github-actions/expressions#literals) in expressions.

**Comment by abitrolly** [comment]
A workaround is to use `fromJSON()` to remove quotes.

```
      if: github.ref == format('refs/heads/{0}', fromJSON('"master"'))
```

**Comment by JamesMGreene** [comment]
That's an interesting observation, thank you for reporting it!

The hydration of a starter workflow from the templates is something handled within the GitHub backend, so I'll try to get someone to take a further look from that perspective. 🔍 

With YAML, it seems to me that we would generally be fine in most cases just omitting the quotes, and leaving such things up to the starter workflow templates themselves to include when necessary. 🤔

**Comment by perj** [comment]
I just ran into this exact issue. Template expanded to 
```
    if: github.ref_name == '"main"'
```
which doesn't work.

`fromJSON` seems to be the easiest workaround.

**Comment by abitrolly** [comment]
I believe it is still actual and not fixed.

**Comment by ttloves2** [comment]
if: github.ref == 'refs/heads/main'
