### ISSUE TITLE
Suggestion to add Vite GitHub pages workflow

### ISSUE THREAD

**Issue by kolibril13** [actions/starter-workflows#2119]
The github-pages workflow for hosting a react app on a static page with vite https://vitejs.dev/guide/static-deploy.html#github-pages is amazing!

To increase the visibility, it would be nice if this could be mentioned in the Github Actions tab under the category "Pages": 

<img width="1198" alt="image" src="https://github.com/vitejs/vite/assets/44469195/a8a8673b-8475-45ae-ac8d-b01e422514a2">

And here is a proof that this workflow actually works: https://github.com/Octoframes/mafs-bezier

Issue first posted at https://github.com/vitejs/vite/issues/13877 cc @patak-dev

**Comment by sledzikteo** [comment]
main
