### ISSUE TITLE
Django example

### ISSUE THREAD

**Issue by lorepieri8** [actions/starter-workflows#212]
It would be useful to have a yml example for Django. It is actually named in the readme (ci/python-django.yml), but there is nothing in the ci folder.

**Comment by sobolevn** [comment]
I wonder if that's appropriate to add our config for it.
We use https://github.com/wemake-services/wemake-django-template

And `wemake-python-styleguide`: https://github.com/wemake-services/wemake-python-styleguide, it is the strictest `python` linter out there that also does automated code-reviews:

![wps](https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/docs/_static/reviewdog.png)

Docs: https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/github-actions.html

Feel free to ping / assign me if I can help with this one.
