### ISSUE TITLE
php-versions in matrix always deploys php 7.3

### ISSUE THREAD

**Issue by zopyx** [actions/starter-workflows#216]
I have this "PHP Composer" start workflow for a project specifying PHP 7.1-7.3

https://github.com/zopyx/zopyx.php.smashdocs/blob/master/.github/workflows/php.yml

One step calls `php --version`.

The step output always php 7.3 as version for all runs from 7.1 to 7.3

![screenshot-github com-2019 11 20-16_38_21](https://user-images.githubusercontent.com/594239/69253091-55d0fd80-0bb4-11ea-8daf-7407c6e0da99.png)

**Comment by shivammathur** [comment]
@zopyx 
That is correct behaviour, specifying `php-versions` in `matrix.strategy` will not change the PHP version.
I created an action you can use to do this [shivammathur/setup-php](https://github.com/shivammathur/setup-php)

**Comment by anthonysterling** [comment]
@shivammathur is correct here, AFAIK, that matric will not install/configure multiple versions of the PHP runtime - I'll close this for now, but feel free to re-open if you think this is incorrect and I'll dig some more. 👍
