### ISSUE TITLE
Default Haskell CI is broken

### ISSUE THREAD

**Issue by ericpashman** [actions/starter-workflows#228]
The `haskell.yml` provided for CI specifies a broken build process. The config specifies v3.0 of Cabal and then proceeds to run:

    cabal install --only-dependencies --enable-tests

An error results and the build fails.

The problem is that those two options do not work together, and have not ever worked together for the `new-`style Cabal commands (which Cabal v3.0 renamed to remove the `new-` prefixes); see https://github.com/haskell/cabal/issues/5650 for details.

**Comment by vp2177** [comment]
@ericpashman Is the error in question `cabal: --enable-tests was specified, but tests can't be enabled in a remote package` ?

**Comment by ericpashman** [comment]
Yes.
