### ISSUE TITLE
[error]Process completed with exit code 5.

### ISSUE THREAD

**Issue by timmy61109** [actions/starter-workflows#233]
Hello, I use GitHub Actions to check my Python program and use your script as an example. Although I have modified it, I may also modify it wrong, but I found that whether it is modified by you or myself, After creating on Azure DevOps Pipelines, the following error message will appear, but I do n’t know why, after querying the Internet.

```
Installing collected packages: attrs, more-itertools, zipp, importlib-metadata, pluggy, six, pyparsing, packaging, wcwidth, py, pytest
Successfully installed attrs-19.3.0 importlib-metadata-0.23 more-itertools-7.2.0 packaging-19.2 pluggy-0.13.1 py-1.8.0 pyparsing-2.4.5 pytest-5.3.1 six-1.13.0 wcwidth-0.1.7 zipp-0.6.0
============================= test session starts ==============================
platform linux -- Python 3.7.5, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
rootdir: /home/runner/work/Introduction-to-Programming-Using-Python/Introduction-to-Programming-Using-Python
collected 0 items

============================ no tests ran in 0.48s =============================
##[error]Process completed with exit code 5.
```

But I do n’t know why this is the case. There is no clear answer to the query on the Internet. It may be related to the setting of the container. I feel that I do not have permission to write to the files generated by pytest or flake8.

The following is my script. Although there are some problems after the modification, it started with the example provided by this project:  
[pythonpackage.yml](https://github.com/timmy61109/Introduction-to-Programming-Using-Python/blob/master/.github/workflows/pythonpackage.yml)  
[pythonapp.yml](https://github.com/timmy61109/Introduction-to-Programming-Using-Python/blob/master/.github/workflows/pythonapp.yml)

This is the output:  
[GitHub Actions of Introduction-to-Programming-Using-Python](https://github.com/timmy61109/Introduction-to-Programming-Using-Python/actions)

Above is Google Translate

**Comment by Diima7** [comment]
I have the same Problem

**Comment by timmy61109** [comment]
@Diima7 I've solved it, maybe I can help you solve it.

**Comment by ysfchn** [comment]
@timmy61109 Can you say how did you solved it? It would be helpful for me and people who coming from search results.

**Comment by timmy61109** [comment]
I can help your CI work with actual actions. I have forked your repository, and then helped you to fix the mistakes, then pull the request and tell why, so of course you can ask questions about the changes.

Translated by Google Translator

**Comment by timmy61109** [comment]
The deployment can use Flake8 and Pylint to do Lint first. Pytest needs to write a module. Through this module to check other modules and functions, so Pytest will be more difficult, that is, he will need to call for other programs ,E.g:

![image](https://user-images.githubusercontent.com/38396747/72037391-f4d2c580-32d8-11ea-9d74-d86d7f4d9f19.png)

Therefore, Pytest is used to check functions, and even function check functions. At present, the environments provided by major platforms do not allow dry run, so the above problems occur.

Such as using Pylint and Flake8 are static checks, so they can be fully implemented, for example:

![image](https://user-images.githubusercontent.com/38396747/72037531-7fb3c000-32d9-11ea-9bf5-9ac7b95fedb6.png)

![image](https://user-images.githubusercontent.com/38396747/72037541-91956300-32d9-11ea-807d-c1eca39f105b.png)

So I can help your CI work with actual actions. I can forked your repository, and then helped you to fix the mistakes, then pull the request and tell why, so of course you can ask questions about the changes.

Translated by Google Translator

**Comment by ysfchn** [comment]
@timmy61109 That would be cool, I actually need help setting CI about my repository called AI-Kit 😁

**Comment by timmy61109** [comment]
@ysfchn You can give me the repository you need to build, I can help you build it, I will use Pylint and Flake8 first, and then you need to tell me how you need to call your function, or you can write your own check Program.

**Comment by JavascriptLearner815** [comment]
Same problem.

**Comment by timmy61109** [comment]
> Mine is related to this, I made a workflow with the python starter workflow and it returned exit code 5.

I can help you, but I need you to tell me which project is yours

**Comment by JavascriptLearner815** [comment]
https://github.com/JavascriptLearner815/The-Dean-Site/actions/runs/210487668

**Comment by timmy61109** [comment]
> https://github.com/JavascriptLearner815/The-Dean-Site/actions/runs/210487668

I found that you don’t have Python code and packages to provide checks. For Pytest, you need Python code to provide checks.

**Comment by timmy61109** [comment]
@JavascriptLearner815 Do you need to develop any software or features? Maybe I will be interested.

**Comment by JavascriptLearner815** [comment]
So I added a very, very tiny bit of code into it, and it again said in pytest returned exit code 5.        

Are Windows and GitHub exit codes different? 

I mean, GitHub Actions is kind of simulating a terminal here, and noticing that it says the same message twice, it might be what I think it is - access is denied.

**Comment by timmy61109** [comment]
@JavascriptLearner815 Maybe you can open a new branch in your project and put your small code on it. I can demonstrate how to run Pytest on it according to your code.

Then Windows exits are the same, which is what I can guarantee to you.

At first I thought the reason was the same as you thought, but in fact it is not because of dry running.

**Comment by PouekDEV** [comment]
I have same problem my repository https://github.com/PouekDEV/ChamsterBot/runs/1362577358

**Comment by timmy61109** [comment]
> I have same problem my repository https://github.com/PouekDEV/ChamsterBot/runs/1362577358

I have looked at your repository because of dry run, and you have to write a test function for Pytest to check.

**Comment by PouekDEV** [comment]
Ok nevermind I just got rid of this workflow

**Comment by timmy61109** [comment]
> Ok nevermind I just got rid of this workflow

I can help you, I already fork your repository

**Comment by PouekDEV** [comment]
> > Ok nevermind I just got rid of this workflow
> 
> I can help you, I already fork your repository

If you want but I don't need it anymore

**Comment by timmy61109** [comment]
> > > Ok nevermind I just got rid of this workflow
> > 
> > 
> > I can help you, I already fork your repository
> 
> If you want but I don't need it anymore

So you don’t want to continue your project?

**Comment by PouekDEV** [comment]
> > > > Ok nevermind I just got rid of this workflow
> > > 
> > > 
> > > I can help you, I already fork your repository
> > 
> > 
> > If you want but I don't need it anymore
> 
> So you don’t want to continue your project?

I will continue project if I will have any idea what to add. This is whole point of what I'm making with it. I don't need anymore this workflow that is what i meant.

**Comment by timmy61109** [comment]
I got it thanks

**Comment by PouekDEV** [comment]
> I got it thanks

No problem

**Comment by erikfilias** [comment]
@timmy61109 , I have the same problem...But I don't know how to solve it since it said the `imp module` is deprecated.
Any idea? Thanks in advance.

Link: https://github.com/IIT-EnergySystemModels/openTEPES/runs/1473273369?check_suite_focus=true

**Comment by timmy61109** [comment]
> @timmy61109 , I have the same problem...But I don't know how to solve it since it said the `imp module` is deprecated.
> Any idea? Thanks in advance.
> 
> Link: https://github.com/IIT-EnergySystemModels/openTEPES/runs/1473273369?check_suite_focus=true

I know why, you can refer to the following, I suggest you ignore it first.

https://github.com/PyUtilib/pyutilib/issues/111

And your code is quite messy, it is recommended to write in accordance with PEP8 style.

**Comment by erikfilias** [comment]
> And your code is quite messy, it is recommended to write in accordance with PEP8 style.

Thank you, I'll try to rewrite it.

**Comment by APratham** [comment]
@timmy61109 Hi, I need a small help. This is a Twitter bot, can you please help me setup the workflow for [this](https://github.com/APratham/retweet-bot/actions/runs/395288091) too? Maybe one of the reasons it is failing because it isn't a complete Python program maybe? Do I need to add something else to the repository? Also thank you so much for all the help you've been doing.

**Comment by timmy61109** [comment]
@APratham Hello, there is a problem with your link, I can't find it.

Are you in a hurry now? Because my work is behind schedule this week, I will be able to help you next week.

**Comment by APratham** [comment]
Sorry, I made it a private repo because it contains the credentials. If needed I can add you as a collaborator on the repo then you can access it. Sure please take your time. Let me know when you are free so we can proceed

**Comment by timmy61109** [comment]
> Sorry, I made it a private repo because it contains the credentials. If needed I can add you as a collaborator on the repo then you can access it. Sure please take your time. Let me know when you are free so we can proceed

Otherwise you can add me to your project first, and then I can help you when I have time

**Comment by zinwayz** [comment]
> > Sorry, I made it a private repo because it contains the credentials. If needed I can add you as a collaborator on the repo then you can access it. Sure please take your time. Let me know when you are free so we can proceed
> 
> Otherwise you can add me to your project first, and then I can help you when I have time
I DON'T KNOW HOW TO ADD YOU

**Comment by APratham** [comment]
@zinwayz He wasn't referring to you. Also please don't type in all caps, it is sometimes interpreted as shouting 👍 

@timmy61109 Yes sure I will add you. Then you can work on it whenever you have time

**Comment by timmy61109** [comment]
Haha, sorry, I am funny.

@zinwayz If you have a project that needs help, you can add me to your project.

@APratham Okay, I got it, and I have also joined it.

**Comment by wajahat414** [comment]
I have also the same error, can you help me please

**Comment by timmy61109** [comment]
> I have also the same error, can you help me please

Ok, Please your project.

**Comment by flopp999** [comment]
@timmy61109 maybe you can have a look on my code? Thanks
https://github.com/flopp999/Tibber-InfluxDB/actions/runs/614455552
I think I need to add some test code, but how and where?
I want to add variable "token" and then see what the Print on LINE 36 will show

**Comment by timmy61109** [comment]
> @timmy61109 maybe you can have a look on my code? Thanks
> https://github.com/flopp999/Tibber-InfluxDB/actions/runs/614455552
> I think I need to add some test code, but how and where?
> I want to add variable "token" and then see what the Print on LINE 36 will show

OK

**Comment by timmy61109** [comment]
> I have also the same error, can you help me please

please get me your code.

**Comment by flopp999** [comment]
Hi

https://github.com/flopp999/Tibber-InfluxDB/blob/main/.github/workflows/python-app.yml


/Daniel
________________________________
Från: Wu Chenzhi <notifications@github.com>
Skickat: Friday, March 5, 2021 7:25:09 AM
Till: actions/starter-workflows <starter-workflows@noreply.github.com>
Kopia: flopp999 <danielnilsson79@hotmail.com>; Comment <comment@noreply.github.com>
Ämne: Re: [actions/starter-workflows] [error]Process completed with exit code 5. (#233)


I have also the same error, can you help me please

please get me your code.

**Comment by timmy61109** [comment]
@flopp999 Sorry for my late reply, I have been busy recently. Your problem is the same as everyone else, Pytest Run dry! So you need to make Pytest something to work.

**Comment by timmy61109** [comment]
@flopp999 In addition, I also found that your program has not been written in accordance with the style, so there will be errors and fail the inspection.

**Comment by vikas-15** [comment]
i am also facing same error https://github.com/vikas-15/Demo-GitHub-Action/runs/6156677256?check_suite_focus=true

**Comment by timmy61109** [comment]
> i am also facing same error https://github.com/vikas-15/Demo-GitHub-Action/runs/6156677256?check_suite_focus=true

You need to have a program for it to run tests, currently your repository doesn't have anything related to Python, so you will get errors when running CI.

**Comment by jrishabh731** [comment]
I'm facing the same issue.  
This is my workflow.
https://github.com/jrishabh731/FastAPI_BlueYonder/blob/7863c1d32d2af87a3df7f9471f3a6d4778ba36ca/.github/workflows/docker-image.yml

Error : 
Run docker-compose exec -T api_server pytest /by/unittest/
  
============================= test session starts ==============================
platform linux -- Python 3.9.13, pytest-[7](https://github.com/jrishabh731/FastAPI_BlueYonder/runs/7228251220?check_suite_focus=true#step:8:8).1.2, pluggy-1.0.0
rootdir: /by
collected 0 items
============================ no tests ran in 0.00s =============================
Error: Process completed with exit code 5.


On local environment:

[root@rtm5 FastAPI_BlueYonder]# docker-compose exec -T api_server pytest /by/unittest/ -v
============================= test session starts ==============================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /by
collecting ... collected 2 items

../unittest/testcase/test_api.py::test_get_engine_inspection PASSED      [ 50%]
../unittest/testcase/test_api.py::test_post_engine_inspection PASSED     [100%]

============================== 2 passed in 0.34s ===============================
[root@rtm5 FastAPI_BlueYonder]#

**Comment by TechWiz-3** [comment]
Is your repo private? I can't access the link and it doesn't show on your profile

**Comment by TechWiz-3** [comment]
Line 5 in `test_api.py` is `sys.path.append("/by/source/")` a real directory?

**Comment by jrishabh731** [comment]
Yeah. Its under the container. 
Structure is
/by/source
     /unittest

from unittest I was not able to call the source files or function thus added this path.

**Comment by jrishabh731** [comment]
Thanks for the efforts! I'm able to resolve it. The container was not running due to some host issues. Resolved that and it works.

**Comment by TechWiz-3** [comment]
Glad to hear that 😌 good work

**Comment by lomWs** [comment]
I have also the same error, can you help me please
link : https://github.com/lomWs/mp3_converter/actions/runs/3890088579/jobs/6638914895#step:6:14

**Comment by timmy61109** [comment]
> 我也有同樣的錯誤，你能幫我嗎請 鏈接：[https://github.com/lomWs/mp3_converter/actions/runs/3890088579/jobs/6638914895#step :6:14](https://github.com/lomWs/mp3_converter/actions/runs/3890088579/jobs/6638914895#step:6:14)

OK, no problem

**Comment by timmy61109** [comment]
@lomWs You, have not test program, so error

**Comment by Ioome** [comment]
o damn it，thank for you , I have been solved.😊

**Comment by UnnormalPerson** [comment]
Hi! I am a newbie in both python and github and um would like to ask for help on why is my code not running with pytest. [I want to run Unstable.py (Its named like that only because I am having problems with the code and newly moved to github hoping people can help :) )] Link: https://github.com/UnnormalPerson/Scissors-Paper-Stone To whoever who can help, thanks a lot!
如果你不读英语，我是想说，我刚刚开始学用python和github，我写的代码有个问题，那就是pytest没收到哪一个代码，(Unstable.py)，我不知道为什么会这样，有人可以帮帮我吗？（我没用狗哥翻译：））谢了！ 对了，连接是：https://github.com/UnnormalPerson/Scissors-Paper-Stone

**Comment by UnnormalPerson** [comment]
Wait, diff problem
等一下，不一样
2s
0s
0s
4s
1s
0s
Run pytest
============================= test session starts ==============================
platform linux -- Python 3.[1](https://github.com/UnnormalPerson/Scissors-Paper-Stone/actions/runs/5208550542/jobs/9397272644#step:6:1)0.11, pytest-[7](https://github.com/UnnormalPerson/Scissors-Paper-Stone/actions/runs/5208550542/jobs/9397272644#step:6:8).3.1, pluggy-1.0.0
rootdir: /home/runner/work/Scissors-Paper-Stone/Scissors-Paper-Stone
collected 0 items / 1 error

==================================== ERRORS ====================================
______________________ ERROR collecting test_Unstable.py _______________________
ImportError while importing test module '/home/runner/work/Scissors-Paper-Stone/Scissors-Paper-Stone/test_Unstable.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.[10](https://github.com/UnnormalPerson/Scissors-Paper-Stone/actions/runs/5208550542/jobs/9397272644#step:6:11).[11](https://github.com/UnnormalPerson/Scissors-Paper-Stone/actions/runs/5208550542/jobs/9397272644#step:6:12)/x64/lib/python3.10/importlib/__init__.py:[12](https://github.com/UnnormalPerson/Scissors-Paper-Stone/actions/runs/5208550542/jobs/9397272644#step:6:13)6: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_Unstable.py:2: in <module>
    import ipywidgets as widgets
E   ModuleNotFoundError: No module named 'ipywidgets'
=========================== short test summary info ============================
ERROR test_Unstable.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.12s ===============================
Error: Process completed with exit code 2.

**Comment by timmy61109** [comment]
> Hi! I am a newbie in both python and github and um would like to ask for help on why is my code not running with pytest. [I want to run Unstable.py (Its named like that only because I am having problems with the code and newly moved to github hoping people can help :) )] Link: https://github.com/UnnormalPerson/Scissors-Paper-Stone To whoever who can help, thanks a lot! 如果你不读英语，我是想说，我刚刚开始学用python和github，我写的代码有个问题，那就是pytest没收到哪一个代码，(Unstable.py)，我不知道为什么会这样，有人可以帮帮我吗？（我没用狗哥翻译：））谢了！ 对了，连接是：https://github.com/UnnormalPerson/Scissors-Paper-Stone @timmy61109

OK

我最近會花時間幫你看

**Comment by UnnormalPerson** [comment]
@timmy61109 经过一些更改我有可能把它弄得更乱，也不小心删除掉了，对不起！

**Comment by timmy61109** [comment]
> @timmy61109 经过一些更改我有可能把它弄得更乱，也不小心删除掉了，对不起！希望你能帮我把它回原。

好的

**Comment by timmy61109** [comment]
基本上你的沒有測試程式也沒有對應的規則與資料，這樣一定會有錯誤

**Comment by timmy61109** [comment]
你的程式是作什麼的？

**Comment by UnnormalPerson** [comment]
我只是有一写完一边把它试一下，因为我刚刚开始用这个程序，不会试自己写的东西。（Test Python code) 对不起我很笨:)

**Comment by yvonnegalusha** [comment]
Does pytest support opening text files and doing file comparisons in unit tests? My unit tests work in Spyder, but not github autograder. I assume it is the pytest environment that I do not have installed correctly. The tests exit with error: code 5 and here is my setup command:  sudo -H pip3 install pytest pytest-openfiles
Any help is appreciated.

**Comment by timmy61109** [comment]
> pytest 是否支持在單元測試中打開文本文件並進行文件比較？我的單元測試可以在 Spyder 中運行，但不能在 github autograder 中運行。我認為這是我沒有正確安裝的pytest環境。測試退出時出現錯誤：代碼 5，這是我的設置命令： sudo -H pip3 install pytest pytest-openfiles 感謝任何幫助。

你可以提供你的程式碼，然後可以幫助您，只是最近很忙，通常幫助的方式都是會協助改寫測試檔案，因此最近只能告訴您錯誤原因，但無法實質幫助。

**Comment by timmy61109** [comment]
> 我只是有一写完一边把它试一下，因为我刚刚开始用这个程序，不会试自己写的东西。（Test Python code) 对不起我很笨:)

測試程式是透過你提供一組資料，然後將資料丟進測試你撰寫的函式，如果資料一致回傳 True ，資料輸出結果是 False 就錯誤，這個是最簡單的測試方式。

**Comment by timmy61109** [comment]
> pytest 是否支持在單元測試中打開文本文件並進行文件比較？我的單元測試可以在 Spyder 中運行，但不能在 github autograder 中運行。我認為這是我沒有正確安裝的pytest環境。測試退出時出現錯誤：代碼 5，這是我的設置命令： sudo -H pip3 install pytest pytest-openfiles 感謝任何幫助。

Spyder 因為是整合環境，很有可能你在 github 上有缺少相依的套件，因此無法運行，這點要注意。

全新空白的環境壞處是要自己建構，好處是了解自己的軟體相依的最小套件是什麼

**Comment by timmy61109** [comment]
> 我只是有一写完一边把它试一下，因为我刚刚开始用这个程序，不会试自己写的东西。（Test Python code) 对不起我很笨:)

我沒辦法看到你的專案了

**Comment by timmy61109** [comment]
> Does pytest support opening text files and doing file comparisons in unit tests? My unit tests work in Spyder, but not github autograder. I assume it is the pytest environment that I do not have installed correctly. The tests exit with error: code 5 and here is my setup command: sudo -H pip3 install pytest pytest-openfiles Any help is appreciated.

You can provide your program code and we can help you. It's just that I've been very busy lately.

In the past I've helped by rewriting the test files, so lately I've been able to tell you the cause of the error, but not actually help.
