### ISSUE TITLE
Change dir (cd) comand is not working

### ISSUE THREAD

**Issue by diegohdez90** [actions/starter-workflows#2352]
In my workflow I set this command in my build job:

```yml
      - name: change dir
      run: cd <directory_name>
```

And this is not updating the pwd it's the same as working directory.  Fix this bug.

**Comment by elbrenn** [comment]
This repo is for feedback on starter workflows specifically. For general Actions requests, please follow [support process](https://docs.github.com/en/support/sharing-feedback-with-github) for assistance
