### ISSUE TITLE
Scala builds with SBT do not seem to work anymore

### ISSUE THREAD

**Issue by tovbinm** [actions/starter-workflows#247]
The `sbt test` command does not run tests anymore.

<img width="570" alt="Screen Shot 2019-12-06 at 2 38 33 PM" src="https://user-images.githubusercontent.com/629845/70361386-371a6a00-1836-11ea-9563-ae214b5475d2.png">

The next (and the last line) after that is `Copying runtime jar.` and neither the tests are executed nor an error is produced.

**Comment by WritersWritingWordsbeingcharacters** [comment]
Are you talking to me Mattews?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sim642** [comment]
I just noticed that the same thing has started happening on my repo because suddenly the builds got much faster: https://github.com/sim642/adventofcode/actions.

**Comment by tovbinm** [comment]
In the meantime I switched to https://github.com/olafurpg/setup-scala

**Comment by ethomson** [comment]
Since https://github.com/sbt/sbt/issues/5270, is this now resolved?

**Comment by tovbinm** [comment]
yes! thank you.
