### ISSUE TITLE
Update php 7.4 in ubuntu-latest

### ISSUE THREAD

**Issue by alihasana** [actions/starter-workflows#253]
Hi,

I got the error, while using php 7.4 in my project 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.4.0 but your PHP version (7.3.12) does not satisfy that requirement.
  Problem 2
    - Installation request for ocramius/proxy-manager 2.5.0 -> satisfiable by ocramius/proxy-manager[2.5.0].
    - ocramius/proxy-manager 2.5.0 requires php ^7.4.0 -> your PHP version (7.3.12) does not satisfy that requirement.
  Problem 3
    - ocramius/proxy-manager 2.5.0 requires php ^7.4.0 -> your PHP version (7.3.12) does not satisfy that requirement.
    - doctrine/migrations 2.2.0 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.5.0].
    - Installation request for doctrine/migrations 2.2.0 -> satisfiable by doctrine/migrations[2.2.0].
```

I try to use [package](https://github.com/marketplace/actions/setup-php-action) from maketplace but it takes 1:30 min to install php in every action 

please let me when ubutu latest will get update php 7.4 in default

**Comment by anthonysterling** [comment]
AFAICT there are no Ubuntu releases that ship with PHP 7.4, the latest snapshot build of Ubuntu is only running `7.3.11`.

**Comment by spaze** [comment]
The deb.sury.org repo (already used) contains 7.4.

**Comment by spaze** [comment]
@alihasana I can now use PHP 7.4 on ubuntu latest without installing any other action.

**Comment by alihasana** [comment]
thanks
Cordialement,

SHAIK ALAUDDEEN Alihasana <hasana.ali@gmail.com>

View My linkedIN Page <https://www.linkedin.com/in/alihasana/>



Le ven. 31 janv. 2020 à 18:52, Michal Špaček <notifications@github.com> a
écrit :

**Comment by alihasana** [comment]
php 7.4 is updated in git action
