### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by Diakite12** [actions/starter-workflows#277]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by ethomson** [comment]
Hello - it looks you may have opened an issue with our default issue template.  I'm going to close this, but if you have an issue to report or a feature to request, please don't hesitate to open another issue with the details.  Thanks!
