### ISSUE TITLE
Dart starter workflow does not install chrome

### ISSUE THREAD

**Issue by UnHumbleBen** [actions/starter-workflows#305]
If I specify chrome platform in `dart_test.yaml`, the tests run by the virtual environment fails:

```
'Failed to load "test/reducer_test.dart":
  Failed to run Chrome: No such file or directory
    Command: google-chrome --user-data-dir=/tmp/dart_test_CMARKO http://localhost:41421/jcX5JOhelDwsysczN6MgRzGHJr7UNIsO/packages/test/src/runner/browser/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A41421%2FjcX5JOhelDwsysczN6MgRzGHJr7UNIsO%2F0&debug=false --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate --disable-dev-shm-usage --headless --disable-gpu --remote-debugging-port=0.
```

The error indicates that Chrome is not installed on the virtual environment.

Here is my dart.yml
```yml
name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run build_runner test -- -p chrome test/reducer_test.dart
```
and here is my dart_test.yaml

```yaml
# This is a browser-only package, so test on chrome by default.
platforms: [chrome]

filename: "reducer_test.dart"

presets:
  # Pass "-P debug" to enable debugging configuration
  debug:
    pause_after_load: true
    exclude_tags: undebuggable
    reporter: expanded
```

**Comment by CoraCapuyan** [comment]
If I specify chrome platform in dart_test.yaml, the tests run by the virtual environment fails:

'Failed to load "test/reducer_test.dart":
  Failed to run Chrome: No such file or directory
    Command: google-chrome --user-data-dir=/tmp/dart_test_CMARKO http://localhost:41421/jcX5JOhelDwsysczN6MgRzGHJr7UNIsO/packages/test/src/runner/browser/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A41421%2FjcX5JOhelDwsysczN6MgRzGHJr7UNIsO%2F0&debug=false --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate --disable-dev-shm-usage --headless --disable-gpu --remote-debugging-port=0.
The error indicates that Chrome is not installed on the virtual environment.

Here is my dart.yml

name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run build_runner test -- -p chrome test/reducer_test.dart
and here is my dart_test.yaml

# This is a browser-only package, so test on chrome by default.
platforms: [chrome]

filename: "reducer_test.dart"

presets:
  # Pass "-P debug" to enable debugging configuration
  debug:
    pause_after_load: true
    exclude_tags: undebuggable
    reporter: expanded
