### ISSUE TITLE
Get python versions from setup.py?

### ISSUE THREAD

**Issue by endolith** [actions/starter-workflows#310]
Is it possible for python-package.yml to automatically get the python versions from setup.py → `python_requires='>=3.6'`?

**Comment by fabaa** [comment]
`[Obtenez les versions de python [](https://github.com/actions/starter-workflows)

**Comment by SumanaShree53** [comment]
from html.parser import HTMLParser
from urllib.request import urlopen
from urllib import parse
class LinkParser(HTMLParser):
   def handle_starttag(self,tag,attrs):
      if tag=='a':
	     for(key,value)in attrs:
		    if key=='href':
			   newurl=parse.urljoin(self.baseurl,value)
			   self.links=self.links+[newurl]
	def getLinks(self,url):
	   self.links=[]
	   self.baseUrl=url
	   response=urlopen(url)
	   if response.getheader('Content-type')=='text/html':
	       htmlBytes=response.read()
		   htmlString=htmlBytes.decode("utf-8")
		   self.feed(htmlString)
		   return htmlString,self.links
		else:
		   return" ",[]
	def spider(url,word,maxPages):
		pagesToVisit=[url]
		numberVisited=0
		foundWord=False
		while numberVisited<maxPages and pagesToVisit !=[] and not foundWord : numberVisited=numberVisited+1
		   url pagesToVisit[0]
		   pagesToVisit=pagesToVisit[1:]
		   try:
				print(numberVisited,"visiting:",url)
				parser=LinkParser()
				data,Links=parser.getLinks(url)
				if data.find(word)>-1:
					foundWord=True
				pagesToVisit=pagestoVisit+links
				print("**success**")
			except:
				print("**Failed**")
		if foundWord:
			print("The Word",word,"was found at",url)
		else:
			print("word never found")

**Comment by yritetaas** [comment]
[](url)

**Comment by yritetaas** [comment]
https://github.com/actions/starter-workflows/issues/310#issuecomment-590021149

**Comment by konradpabjan** [comment]
An update was rolled out the `actions/setup-python` that now causes the version of Python that was setup to be displayed, and outputted so it can be used in the YAML

See: https://github.com/actions/setup-python/pull/51 and https://github.com/actions/setup-python/issues/50
