### ISSUE TITLE
ci/python-publish.yml: Build Failing due to missing libraries

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [actions/starter-workflows#381]
Workflow: [ci/python-publish.yml](https://github.com/actions/starter-workflows/blob/a87d9c70b65a177a35dfee03ca2d7bc49aa592f6/ci/python-publish.yml)

Job: **Build and publish**
Problem: Build fails due to missing libraries required by the package (usually mentioned in requirements.txt)

Possible Fix: Install the project-specific dependencies as well.

**Comment by ethomson** [comment]
> ...also seeing this as a starter template or general/best practice template, it's a bit concerning from a security-perspective if requirements.txt slips into the publishing stage where PyPi credentials are exposed. They could be handed to a temporary dependency injection and make collateral damages quite big if that was to happen.

Hi @benjaoming - can you recommend a mitigation?

**Comment by benjaoming** [comment]
@ethomson I'm not too familiar with Actions, but from using Buildkite, Circle CI and Travis CI, I would think this is possible: In one container (build job), get the distribution built. In a separate container, import the artifact built in the former job, and do the publishing here, so API keys aren't exposed to anything else than 1) the container itself 2) core pip tools and 3) the NPM project `setup-python` that Github should be responsible for ensuring the safety of.

This should also be a logical structure for CI: Build => Test => Deploy/Publish.

**Comment by Darimac1** [comment]
Deploy ideas = Ideas deploy
Missing libraries =  Libraries missing
Source1 = 1Source

**Comment by Vibhu-Agarwal** [comment]
Fixed in #382
