### ISSUE TITLE
Excellent; this is very helpful. Thanks @1138-4EB

### ISSUE THREAD

**Issue by CLWNRDW** [actions/starter-workflows#392]
Excellent; this is very helpful. Thanks @1138-4EBgot

_Originally posted by @krcroft in https://github.com/actions/starter-workflows/issues/95#issuecomment-539649878_

**Comment by ethomson** [comment]
Hello!  It looks like you may have opened this issue accidentally, or without all the information that you wanted to include.  As a result, I'm going to close this, but please do follow up if you have a concern or issue with the starter workflows.
