### ISSUE TITLE
«Радио - НОД»

### ISSUE THREAD

**Issue by 9k8j7h** [actions/starter-workflows#417]
**### «Радио - НОД» « Несёт правду в народ»! 
https://volnorez.com/radio--nod 
Народное тв."Отечество" 
https://ok.ru/video/1918781169361 
ОТПРАВИТЬ ПУБЛИЧНОЕ ПРИГЛАШЕНИЕ
https://volnorez.com/broadcast/ref/375494
Группа-сообщество : Радио НОД-Народное https://vk.com/clubradionod160855618 
Плей лист: Радио(новостной)
https://vk.com/music/album/68969925_9
группа в одноклассниках : 
https://ok.ru/radionod 
Резервный сайт: #РадиоНОД . 
http://9s4qduumytc3.ukit.me/ 
Сайт: Радио НОД . Добро пожаловать!!! 
http://радионод.рф/ 
Ретранслятор. Радио НОД
https://myradio24.com/49105
https://volnorez.com/catalog/radio/sajt-radionod-rf
Ссылка на канал в телеграмм: https://t.me/RadioNODNarodnoetvOtechestvo
Дополнительная площадка- Радио http://101.ru/profile 
http://radionod.101.ru/ http://101.ru/user/userid/697524
1. Канал Радио НОД на Ютубе: не забудь подписаться!!! 
https://www.youtube.com/user/vladimir5382 
2. Канал Радио НОД** 
https://www.youtube.com/user/shigortmb

**Comment by ethomson** [comment]
Hello!  It looks like you may have opened this issue accidentally, or without all the information that you wanted to include.  As a result, I'm going to close this, but please do follow up if you have a concern or issue with the starter workflows.
