### ISSUE TITLE
Conda Support

### ISSUE THREAD

**Issue by saulshanabrook** [actions/starter-workflows#44]
It would be great to support an easy workflow to get started with CI using [Conda](https://en.wikipedia.org/wiki/Conda_(package_manager)).

**Comment by jan-janssen** [comment]
I played around a bit, and struggle to even install conda manually https://github.com/jan-janssen/scisweeper/pull/1 - somehow I am not able to modify the PATH variable, which causes python to use the the host executable. https://github.com/jan-janssen/scisweeper/pull/1/checks?check_run_id=205481830

**Comment by kangwonlee** [comment]
* I could find an environment variable named `$CONDA`
* So I could use `conda` without manually installing it but I started from scratch instead of modifying this action.
* I am currently working on an action : https://github.com/kangwonlee/setup-conda 
    To be honest, I do not know the JavaScript so I would welcome you comments or suggestions (if saying this here is appropriate)

**Comment by jan-janssen** [comment]
@kangwonlee Yes I found the same, but for some reason I always have to specify the path variable  
`export PATH="/usr/share/miniconda/bin:$PATH"` to use the environment.

**Comment by jan-janssen** [comment]
My updated recipe is available at - https://github.com/jan-janssen/scisweeper/blob/githubactions/.github/workflows/main.yml

**Comment by kangwonlee** [comment]
* According to [jobs.<job_id>.steps](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idsteps)

> Each step runs in its own process in the virtual environment and has access to the workspace and filesystem

* So could it be better to make one step rather longer if you don't want to set path frequently?

**Comment by weiji14** [comment]
>     * I could find an environment variable named `$CONDA`

Yet another workaround. I've managed to prepend `$CONDA/bin` i.e. (/usr/share/miniconda/bin) to the `$PATH` by following the instructions [here](https://github.community/t5/GitHub-Actions/Append-PATH-on-Windows/m-p/31169#M694). Basically add this to the workflow before using conda:

```yaml
    - name: Include $CONDA in $PATH
      run: echo ::add-path::$CONDA/bin
```

**Comment by jamienoss** [comment]
I think for conda >=4.7.10 you'll actually need:

```yml
 - name: Include $CONDA in $PATH
   run: echo ::add-path::$CONDA/condabin  # <--- condabin VS bin
```

and perhaps more as I now get a permissions error, but at least it finds conda which, for me, it did not when using ``$CONDA/bin``.

BTW the OS dist. contents are listed [here](https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions).

**Comment by tvatter** [comment]
https://github.com/vinecopulib/pyvinecopulib/blob/actions/.github/workflows/conda.yml works fine for ubuntu and macos, still struggling with windows...

**Comment by tvatter** [comment]
Anyone has had luck with windows? No luck on that side unfortunately.

**Comment by volpatto** [comment]
Struggling with Windows here as well...

**Comment by mick-id** [comment]
For windows I found that it wasn't activating conda environments. This is a configuration problem because conda needs to be told its in Windows Powershell. The following let me successfully update conda.

```
    - name: Initialize Conda for Powershell
      run: |
        (Get-Command python).Path
        C:\Miniconda/condabin/conda.bat update -n base -c defaults conda
        C:\Miniconda/condabin/conda.bat init powershell
    - name: Update and Start Conda Env
      run: |
        C:\Miniconda/condabin/conda.bat env update --file environment.yml --name base
        C:\Miniconda/condabin/conda.bat activate base
```

It's worth noting that init powershell and activate steps need to be in different steps because the powershell needs to be "restarted" for the init to work

**Comment by ben-heil** [comment]
I added a PR containing solutions for Ubuntu and Windows. Please let me know if anything looks incorrect or if there are better ways to do Windows things that I don't know about.

**Comment by mick-id** [comment]
@ben-heil Have you tested python unittest at all? Do you have any inkling why pytest works?

**Comment by ben-heil** [comment]
> @ben-heil Have you tested python unittest at all? Do you have any inkling why pytest works?

I stuck to pytest since I'm more familiar with it (and it makes the workflow more similar to `python-package.yml`. I don't know enough about unittest to say why it's not working. Since not all the tests run in the linked attached, my guess would be that one of the tests themselves failed. Sorry I can't be more help there though

**Comment by tvatter** [comment]
@ben-heil I'm wondering if it wouldn't be easier to unify all builds in a single job. On windows, one can also use bash by specifying `shell: bash`. Then, the conda exec could be set as a different environment variable depending on the platform, something like:

```
- name: Set-up conda
        run:   |
          if [ "${{ matrix.os }}" != "windows-latest" ]; then
            echo '::set-env name=CONDA_EXEC::${CONDA}/bin/conda'
          else
            echo '::set-env name=CONDA_EXEC::C:\Miniconda\condabin\conda.bat'
          fi
        shell: bash
```
Note that I'm doing not windows vs windows because the former should work for macos-latest too...

And if one intends on continuing to use bash with windows, maybe there would be something like
```
echo ". /c/Miniconda/etc/profile.d/conda.sh" >> ~/.profile
```

**Comment by ben-heil** [comment]
@tvatter That's a good idea, but I haven't been able to get `conda activate` to work correctly. It seems like it works fine in powershell, but fail in bash (or maybe in the ubuntu vm specifically). Unfortunately, I have to use activate when running windows to get the correct python version in the PATH.

**Comment by matthewrmshin** [comment]
Hi, I have made an attempt to write a little container based action for Conda here:
https://github.com/matthewrmshin/conda-action

**Comment by mick-id** [comment]
@matthewrmshin Would you be able to to make this windows compatible? I got an error when I tried to use it

```Run matthewrmshin/conda-action@v1
  with:
    args: conda env update -f ./requirements.yml
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.7.5\x64
##[error]Container action is only supported on Linux```

**Comment by matthewrmshin** [comment]
> @matthewrmshin Would you be able to to make this windows compatible? I got an error when I tried to use it
> 
> ```
>   with:
>     args: conda env update -f ./requirements.yml
>   env:
>     pythonLocation: C:\hostedtoolcache\windows\Python\3.7.5\x64
> ##[error]Container action is only supported on Linux```
> ```

Yes, I'll go and read the docs to see how to turn this into a JavaScript action so it can support Windows as well.

**Comment by bryevdv** [comment]
FYI in case it is useful to anyone else, I was able to install Miniconda on  Linux, OSX, and Windows (gitbash) with the following incantations:
```
      - name: Install Miniconda
        shell: bash
        run: |
          if [[ "${{ runner.os }}" = "Linux" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Linux-x86_64.sh
            curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" = "macOS" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-MacOSX-x86_64.sh
            curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" = "Windows" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Windows-x86_64.exe
            curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
            ./Miniconda3-latest-Windows-x86_64.exe //InstallationType=JustMe //RegisterPython=0 //S
          fi

      - name: Setup paths
        shell: bash
        run: |
          echo "::add-path::$HOME/miniconda3/bin"
          echo "::add-path::$HOME/miniconda3/Scripts"
          echo "::add-path::$HOME/miniconda3/envs/testenv/bin"
          echo "::add-path::$HOME/miniconda3/envs/testenv/Scripts"
```

**Comment by dabana** [comment]
Thanks @ben-heil for your contribution, it got me going real fast.

Anyone has experienced the [cache GitHub action](https://github.com/actions/cache) to improve performance? My tests take 1.5 minutes to run but installing the conda environments and the dependencies takes about 8 to 9 minutes, which is way to much in my opinion. Wasting 80% of my precious Github actions minutes on re-installing dependencies does not seam right.

[Cache GitHub action ](https://github.com/actions/cache) provides info on PIP but nothing on Conda. I have been looking around Google for more info on dependency caching with Conda but did not find anything useful so far (finding relevant Conda documentation is always a pain). 

I have no idea how Conda's dependency caching work and how to use it. Can anyone help?

**Comment by ben-heil** [comment]
I'm not super familiar with caching in Conda either, but [this post](https://github.com/theochem/cgrid/issues/8) might help. If you can find where conda is downloading packages before installing them you should be able to save time by caching the downloaded versions

**Comment by goanpeca** [comment]
I was playing a bit with this and created this action which works for all operating systems. It still requires some attention on activation steps.

https://github.com/goanpeca/action-setup-conda

The activation issues are related to how the shell are executed. Bash and SH shells skip any bash_profile config. The same goes for CMD shells which ignore the `Comand Process/Autorun` entry from the windows registry.

Cheers!

**Comment by goanpeca** [comment]
Added the action on the market place https://github.com/marketplace/actions/setup-miniconda !
