### ISSUE TITLE
Need a better way to describe "build and test" for interpreted languages

### ISSUE THREAD

**Issue by ethomson** [actions/starter-workflows#453]
At the moment, we describe all the CI workflows as "build and test ...".

This makes sense for compiled languages (C, C#, TypeScript).  It makes less sense for things that don't have a compile phase (eg Ruby).  We should:

1. identify the languages that aren't "built"
2. come up with a better verb that indicates that we install the dependencies, or remove it altogether, and just say "test ...".

**Comment by 1Uno** [comment]
Thanks for the info will do.
