### ISSUE TITLE
Recommend using PyPI's API tokens for upload, instead of username+password

### ISSUE THREAD

**Issue by pradyunsg** [actions/starter-workflows#468]
Currently `ci/python-publish.yml` indirectly pushes users to use their PyPI username and password for uploading a package. This should be changed to actively recommend using PyPI's support for [API tokens](https://pypi.org/help/#apitoken).

Aside: "publish a Python package" is automation and not CI IMO.

**Comment by webknjaz** [comment]
> Aside: "publish a Python package" is automation and not CI IMO.

Could be, if between "build" and "publish" it had "run the tests against the pre-built artifacts".

**Comment by 1Uno** [comment]
> Currently `ci/python-publish.yml` indirectly pushes users to use their PyPI username and password for uploading a package. This should be changed to actively recommend using PyPI's support for [API tokens](https://pypi.org/help/#apitoken).
> 
> Aside: "publish a Python package" is automation and not CI IMO.

**Comment by pradyunsg** [comment]
Well, unless... Someone files a PR to fix it.

**Comment by webknjaz** [comment]
Still relevant

**Comment by pradyunsg** [comment]
Well, it'd still be a good idea to make this change.

**Comment by prohde** [comment]
Was it solved in aaea7d2?

**Comment by pradyunsg** [comment]
LGTM!
