### ISSUE TITLE
Question regarding multiple workflows per language

### ISSUE THREAD

**Issue by jared-w** [actions/starter-workflows#479]
The question I have is about how best to address the possibility of implementing multiple examples. 

Currently, in the `actions/new` UI page where you can see all of the starter workflows, there's only one per language. This works well for some languages and ecosystems and less so for others.

In all cases, it pushes the average utility of examples down. If you only have one example, you probably don't want to make it a super dense and scary 200 line boilerplate. You also can't afford to cater for anything more diverse than a "vanilla" hello-world codebase.

For example, even for just JavaScript, I could easily see "simple npm", "simple yarn", "simple typescript", "simple babel", "simple reactjs", etc., all being useful and wanted starters (whether or not they'd belong *in* the repo is another matter). Of course, you also don't want to have thousands of starter templates because the overhead of keeping them updated would become ridiculous; not to mention the potential of having an overwhelming and un-intuitive UX.

That said, many of the `actions/setup-$lang` repostories come with a README containing anywhere from 2-5+ examples of increasing complexity. I feel that, ideally, it would be great to integrate those into the `actions/starter-workflows` repo somehow. The potential increase in discoverability could be a great UX improvement.

Do you have any thoughts on how we can strike a balance between a potentially too simple singular example that doesn't meet many needs vs an overwhelming amount of examples that introduce decision paralysis and overwhelm the beginner (either to the ecosystem or github actions) most likely to use them?

Some thoughts I have are whether it would make sense to follow a pattern of simple+cache, cross-platform, featureful, link-to-more. That is:

- An example with the least amount of code possible that follows caching best practices
- Followed by one that is as cross platform as possible
- Followed by one that shows off the most used unique options of the setup action (`registry-url` for `setup-node`, "specifying a version" for most `setup-X` actions, `stable` for `setup-go`, etc).
- Lastly, a link to the rest of the examples in the `setup-X` repo would be in a comment, probably at the top of the workflow.

Would that be possible? Are there alternative ideas worth kicking around?

**Comment by andymckay** [comment]
Sorry, but we'd like to keep issues related to code in this repository. Thank you 🙇 

If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)

If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)
