### ISSUE TITLE
setup-node /action.yml

### ISSUE THREAD

**Issue by nae-fck** [actions/starter-workflows#484]
name: "Code Scanning - Action"

on:
push:
schedule:
- cron: '0 0 * * 0'

jobs:
Codell-Build:

strategy:
  fail-fast: false

# CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
runs-on: ubuntu-latest

steps:
- name: Checkout repository
  uses: actions/checkout@v2

# Initializes the CodeQL tools for scanning.
- name: Initialize CodeQL
  uses: GitHub/code-action/init@v1
  # Override language selection by uncommenting this and choosing your languages
  # with:
  #   languages: go, javascript, sharp, python, CPP, java

# Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
# If this step fails, then you should remove it and run the build manually (see below).
- name: Autobuild
  uses: GitHub/code-action/autobuild@v1

# ℹ️ Command-line programs to run using the OS shell.
# 📚 https://git.io/JvXDl

# ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
#    and modify them (or add more) to build your code if your project
#    uses a compiled language

#- run: |
#   make bootstrap
#   make release

- name: Perform CodeQL Analysis
  uses: GitHub/code-action/analyze@v1
Thank you for sending in this pull request. Please make sure you take a look at the contributing file. Here are a few things for you to consider in this pull request:

 Include a good description of the workflow.
 Links to the language or tool will be nice (unless it's obvious)
In the workflow and properties files:

 The workflow filename of CI workflows should be the name of the language or platform, in lower case. Special characters should be removed or replaced with words as appropriate (for example, "don't" instead of ".NET").

The workflow filename of publishing workflows should be the name of the language or platform, in lower case, followed by "-publish".

 Includes a matching ci/properties/*.properties.json file.

 Use sentence case for the names of workflows and steps, for example "Run tests".

 The name of CI workflows should only be the name of the language or platform: for example "Go" (not "Go CI" or "Go Build")

 Include comments in the workflow for any parts that are not obvious or could use clarification.

 CI workflows should run on push to branches: [ master ] and pull_request to branches: [ master ].

Packaging workflows should run on release with types: [ created ].

Some general notes:

 This workflow must only use actions that are produced by GitHub, in the organization of the action, or

This workflow must only use actions that are produced by the language or ecosystem that the workflow supports. These actions must be published to the GitHub Marketplace. Workflows using these actions must reference the action using the full 40 character hash of the action's commit instead of a tag. Additionally, workflows must include the following comment at the top of the workflow file:

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
 This workflow must not send data to any 3rd party service except to install dependencies.

 This workflow must not use a paid service or product.

**Comment by nae-fck** [comment]
- [ ] #` Contributor Covenant Code of Conduct

## Our Pledge

In the interest of fostering an open and welcoming environment, we as
contributors and maintainers pledge to make participation in our project and
our community a harassment-free experience for everyone, regardless of age, body
size, disability, ethnicity, sex characteristics, gender identity and expression,
level of experience, education, socio-economic status, nationality, personal
appearance, race, religion, or sexual identity and orientation.

## Our Standards

Examples of behavior that contributes to creating a positive environment
include:

* Using welcoming and inclusive language
* Being respectful of differing viewpoints and experiences
* Gracefully accepting constructive criticism
* Focusing on what is best for the community
* Showing empathy towards other community members

Examples of unacceptable behavior by participants include:

* The use of sexualized language or imagery and unwelcome sexual attention or
  advances
* Trolling, insulting/derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or electronic
  address, without explicit permission
* Other conduct which could reasonably be considered inappropriate in a
  professional setting

## Our Responsibilities

Project maintainers are responsible for clarifying the standards of acceptable
behavior and are expected to take appropriate and fair corrective action in
response to any instances of unacceptable behavior.

Project maintainers have the right and responsibility to remove, edit, or
reject comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to this Code of Conduct, or to ban temporarily or
permanently any contributor for other behaviors that they deem inappropriate,
threatening, offensive, or harmful.

## Scope

This Code of Conduct applies within all project spaces, and it also applies when
an individual is representing the project or its community in public spaces.
Examples of representing a project or community include using an official
project e-mail address, posting via an official social media account, or acting
as an appointed representative at an online or offline event. Representation of
a project may be further defined and clarified by project maintainers.

## Enforcement

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the project team at opensource@github.com. All
complaints will be reviewed and investigated and will result in a response that
is deemed necessary and appropriate to the circumstances. The project team is
obligated to maintain confidentiality with regard to the reporter of an incident.
Further details of specific enforcement policies may be posted separately.

Project maintainers who do not follow or enforce the Code of Conduct in good
faith may face temporary or permanent repercussions as determined by other
members of the project's leadership.

## Attribution

This Code of Conduct is adapted from the [Contributor Covenant][homepage], version 1.4,
available at https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

[homepage]: https://www.contributor-covenant.org

For answers to common questions about this code of conduct, see
https://www.contributor-covenant.org/faq
Duplicate of #

**Comment by ethomson** [comment]
Hello!  It looks like you may have opened this pull request accidentally, or without all the changes that you wanted to include.  As a result, I'm going to close this, but please do follow up if there are changes that you want to make here.
