### ISSUE TITLE
Wrong image tag on docker-publish workflow

### ISSUE THREAD

**Issue by LoicViennois** [actions/starter-workflows#499]
It seems that when we set a custom image name here:
https://github.com/actions/starter-workflows/blob/6adb515f324bc8ef4c0091053438298bbc34a85a/ci/docker-publish.yml#L18
the build will fail before push, on tag creation, here:
https://github.com/actions/starter-workflows/blob/6adb515f324bc8ef4c0091053438298bbc34a85a/ci/docker-publish.yml#L75

I guess it should be 

```
docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
```

**Comment by SolutionWala** [comment]
ci/blank.yml

**Comment by mijndert** [comment]
Just hit the same 'bug'. It should indeed be `docker tag $IMAGE_NAME`.

**Comment by mijndert** [comment]
This has been fixed.

**Comment by ChristophDietrich** [comment]
/close

Its merged now.
