### ISSUE TITLE
Improve "maven-publish.yml"

### ISSUE THREAD

**Issue by Marcono1234** [actions/starter-workflows#539]
Hello,
[`maven-publish.yml`](https://github.com/actions/starter-workflows/blob/master/ci/maven-publish.yml) could probably be improved:
1. Improve command line parameters, see also #538
2. Link to https://github.com/actions/setup-java#apache-maven-with-a-settings-path should be placed directly above `settings-path:` because it is irrelevant for everything else
3. Add link to https://github.com/actions/setup-java#publishing-using-apache-maven in header comment (or to [GitHub Help: Publishing Java packages with Maven](https://help.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-maven))
4. Remove redundant step `name: Build with Maven`, `deploy` already includes `package` so it essentially runs `package` (and all phases before it) twice
Edit: `deploy` would skip compiling (since `package` already did this), but would run tests again.
5. Add `--batch-mode` to `deploy` to prevent output which is intended for interactive console
6. Write out `-s` as `--settings` to make it easier to understand for users who are not familiar with all command line options
7. Change name "Publish to GitHub Packages Apache Maven" to "Publish to GitHub Packages with Maven" to be consistent with other message
8. It might be possible to run `deploy` with `-Dmaven.install.skip=true` to skip installing the package to the local repository since that could cause issues when a cache step is used and a large number of the packages of the project accumulate (only happens if the version of the package changes frequently). Though would be good if someone with more Maven deployment experience could confirm this.

Let me know if you want me to write a pull request.

See also https://github.com/actions/setup-java/issues/75

**Comment by andymckay** [comment]
I'm not a maven user, but a pull request for these changes would be most welcome.
