### ISSUE TITLE
python-publish action does not trigger if the release was first drafted, then published

### ISSUE THREAD

**Issue by thededlier** [actions/starter-workflows#554]
Currently the python-publish action only triggers when a release is created. This works fine if you publish the release without first saving a draft. However, if you first decide to save it as a draft and then publish it, the action is bypassed and never triggered. 

This is because Github actions won't trigger for draft releases but since the release was first created as a draft and then published, it is considered as a publish event.

Instead I think most people would prefer this behaviour.
```
on:
  release:
    types: [published]
```

Would like to know your thoughts on the same

**Comment by follnoob** [comment]
I wondered, why it did not work for me. This issue helped me a lot to fix my problem :)

**Comment by KanhuPadhy** [comment]
Before publishing ,it is better to follow the x.y.z-alpha format as pre-release version where x=Major, y=Minor, and z= Patch and followed by an hyphen with any alpha numeric identifiers
