### ISSUE TITLE
[node.js] npm publish-gpr failed with error 500

### ISSUE THREAD

**Issue by zachguo** [actions/starter-workflows#57]
To reproduce, run the publish-gpr workflow on a private repo with `gpr` successfully configured.
```
...
npm ERR! code E500
npm ERR! 500 Internal Server Error - PUT https://npm.pkg.github.com/@my-scope%2fmy-repo - Internal Server Error
```

**Comment by 0383988090** [comment]
Lam s de nhan được co đe

**Comment by wrg1977** [comment]
https://twitter.com/wrg99

**Comment by okuryu** [comment]
FYI: https://github.com/actions/setup-node/issues/53 may be helpful.

**Comment by zachguo** [comment]
The issue is now gone, probably Github has fixed it.
