### ISSUE TITLE
Android workflow fails for SDK 29

### ISSUE THREAD

**Issue by ncipollo** [actions/starter-workflows#58]
Hello,
While testing the android workflow I noticed the build will fail if the app targets API 29. I see the following build error:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following SDK components:
      platforms;android-29 Android SDK Platform 29
   The SDK directory is not writable (/usr/local/lib/android/sdk)
```
Here's a link to the failed build: https://github.com/ncipollo/mtg-league-android/commit/5b7b8d2f85c0a28d2a98d5908fe02d6b72a671c7/checks

When I downgraded my app to target API 28 everything was 👌

**Comment by chrispat** [comment]
The images should now be up to date with the latest tools.

**Comment by fgsguedes** [comment]
I can still reproduce the issue on a private project that I have.

And still having the same behaviour described initially, build works if build tools are downgraded to 28.

I'll be able to provide an example project in a public repository in a couple of hours in case it can help in any way.

**Comment by ncipollo** [comment]
Hmm, this may be more related to the software environment of the ubuntu VM. It looks like the API 29 SDK isn't installed in that environment, at least according to the docs: https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts

Is there are more specific repository this issue should be moved to?

**Comment by fgsguedes** [comment]
That is a good finding.

Build works fine when building on either MacOS or Windows. It fails only on Ubuntu.

**Comment by tetedoie** [comment]
Duplicate issue https://github.com/actions/starter-workflows/issues/119. It's actually working with 29 build tools if the gradle command is prefixed with sudo.

**Comment by EdricChan03** [comment]
Regarding this issue, I'd reached out to GitHub support about this a while back (on 9 Sep) and have just heard back (on 20 Sep) with the following response:

![Screenshot of response to email from 9 Sep](https://user-images.githubusercontent.com/20047125/65436478-c7125f80-de54-11e9-8255-333341f330b3.jpg)

If you can't read it, here's what it says:

> Hi Edric,
> 
> We will be rolling out an update of the Ubuntu images over the next week which will include Android SDK and Build-Tools 29.
> 
> Thanks,
> Kayla

**Comment by EdricChan03** [comment]
@ncipollo Looks like the update has been rolled out:

![Screenshot of text on GitHub Help page](https://user-images.githubusercontent.com/20047125/65681427-759fe580-e08b-11e9-8064-ec5c5c0f718e.jpg)

[Source](https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts)

I'll verify this on my workflow.

**Comment by string-areeb** [comment]
Working now. Confirmed on a local project

**Comment by ncipollo** [comment]
Same, confirmed in my project as well. Thanks everyone!

**Comment by vitalyster** [comment]
Build tools now 29.0.3, please update?

**Comment by lukas1** [comment]
BUMP. Same issue as @vitalyster

**Comment by rubensousa** [comment]
@vitalyster @lukas1 
You can workaround this issue by running the gradle command with sudo. The build tools should be automatically updated.

```
- name: Build with Gradle
  run: sudo ./gradlew build
```

**Comment by lukas1** [comment]
@rubensousa yes, I know about that, but that can lead to other issues. For now it's my workaround as well, but it would be better if they just updated the build tools on their side.

**Comment by prsolucoes** [comment]
Im still have problems:
https://github.com/ezored/ezored/runs/475737604?check_suite_focus=true

Im migrating from travis and this problem exists now on github actions

**Comment by vincent-paing** [comment]
Same issue for Android-R
