### ISSUE TITLE
actions/starter-workflows takes precedence over internal workflow defined in .github repository.

### ISSUE THREAD

**Issue by 3h4x** [actions/starter-workflows#603]
Hey!
We tried creating a terraform workflow in our [cloudposse/.github](https://github.com/cloudposse/.github) repo, but noticed that the one from starter-workflows takes precedence. 
What we did was create [`terraform.yml` and it's json properties](https://github.com/cloudposse/.github/tree/9071c74a2bf77f9ed53001e3d7ce279ef6922767/workflow-templates). After merging to `master` branch new internal workflow showed in our organization (screenshot attached) but after trying to use it (Setup workflow), the default hashicorp one was ought to be commited.  
<img width="413" alt="Screenshot 2020-07-23 at 18 17 36" src="https://user-images.githubusercontent.com/6998565/88312830-f0b94300-cd12-11ea-89c2-b206473a6510.png">
<img width="945" alt="Screenshot 2020-07-23 at 16 50 04" src="https://user-images.githubusercontent.com/6998565/88312883-029ae600-cd13-11ea-8f3e-9696899beea4.png">

We can't find where this behavior is documented. Our expected behavior is the workflow from our org would take precedence.

**Comment by cdb** [comment]
Thanks for pointing this out @3h4x, good find! We have made an internal issue to track it and will update here when we have a fix.
