### ISSUE TITLE
pylint action is broken

### ISSUE THREAD

**Issue by FelixBenning** [actions/starter-workflows#636]
In https://github.com/actions/starter-workflows/blob/main/ci/pylint.yml, the last line:

```shell
pylint `ls -R|grep .py$|xargs`
```

does not work as intended. `ls -R | grep .py$` lists all files with the `.py` ending. Only the *files* not the path to them. So it will find `.py` files in a subdirectory, and pass them to pylint which is then unable to find them on the top level. Causing errors like this:

```bash
vscode@5aa8d281d9b3:/workspaces/lazyConfig$ ls -R|grep .py$
setup.py
__init__.py
config.py
lazyData.py
__init__.py
config.py
lazyData.py
__init__.py
smoke_test.py
vscode@5aa8d281d9b3:/workspaces/lazyConfig$ pylint config.py
************* Module config.py
config.py:1:0: F0001: No module named config.py (fatal)
vscode@5aa8d281d9b3:/workspaces/lazyConfig$ 
```

I'll see if I can fix this and open a pull request if I can find a good fix.

**Comment by leftour** [comment]
![1604090159820-1170129144](https://user-images.githubusercontent.com/73660885/97754648-2b8ffb80-1af8-11eb-87ad-3db58f4da679.jp) الان أحتاج البرامج انا لدي نشام أندرويد إذن فل نبحث التطبيقات التي يمكن وهي استعمالها

**Comment by Toppole69** [comment]
#80

**Comment by jDavidnet** [comment]
I've noticed 2 core problems with the current workflow script.
* it doesn't correctly ingest python scripts in a directory
* it didn't correctly install the requirements for other modules

Here is the corrected code that works on my current workflow, this is based on the above pull request, with some additional fixes.

```python
name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
        tee pylint.txt
    - name: Upload pylint.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pylint report
        path: pylint.txt
```

**Comment by FelixBenning** [comment]
not stale:  just merge the pull request (#637) already

**Comment by SenorPez** [comment]
Absolutely unbelievable that a core function is broken and unfixed.

**Comment by Phil7789** [comment]
> I've noticed 2 core problems with the current workflow script.
> 
> * it doesn't correctly ingest python scripts in a directory
> * it didn't correctly install the requirements for other modules
> 
> Here is the corrected code that works on my current workflow, this is based on the above pull request, with some additional fixes.
> 
>     - name: Analysing the code with pylint
>       run: |
>         python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
>         tee pylint.txt
>     - name: Upload pylint.txt as artifact
>       uses: actions/upload-artifact@v2
>       with:
>         name: pylint report
>         path: pylint.txt
> ```

I've copied this code / the code from the PR
I've noticed that using `python -m pylint` like in your example instead of just pylint like in the PR the --fail-under flag doesn't work and always passes, although the score is below the threshold.

**Comment by thecesrom** [comment]
I've had success running the following:

```yaml
      run: |
        pylint $(git ls-files '*.py')
```

**Comment by mehran-sayyah** [comment]
Hi

**Comment by thecesrom** [comment]
#1108

**Comment by thecesrom** [comment]
With #1108 merged, this can be closed.
