### ISSUE TITLE
Python template: step name formatting error from a matrix variable

### ISSUE THREAD

**Issue by 404NetworkError** [actions/starter-workflows#64]
Running the default Python template shows a step name as: 
`${{ format('Set up Python {0}', matrix.python-version) }}`

It appears the [template](https://github.com/actions/starter-workflows/blob/4634ff455508f20e2ed2ea8d232cd6d40c30d982/ci/python-package.yml#L16) is attempting to set the step name using the `python-version` variable from the matrix.

**Comment by s0lst1ce** [comment]
I have the same issue.

**Comment by andymckay** [comment]
I think this fixed and it is working for me in a quick test. Please let me know if that's not the case. Thank you @404NetworkError and @s0lst1ce 🙇
