### ISSUE TITLE
Broken step name

### ISSUE THREAD

**Issue by Eomm** [actions/starter-workflows#65]
Hi,
I'm trying the GH actions for CI with some Node.js projects.

This default name format
https://github.com/actions/starter-workflows/blob/4634ff455508f20e2ed2ea8d232cd6d40c30d982/ci/node.js.yml#L16

Writes this output:

![image](https://user-images.githubusercontent.com/11404065/63597308-6970c600-c5bd-11e9-9344-a36870456f3e.png)

You can check [here](https://github.com/voxpelli/node-fulfills/pull/3/checks?check_run_id=192392031) or [here with two params](https://github.com/Eomm/fastify-schema-constraint/runs/201506512)

Could you suggest me how to fix this?
Thks

**Comment by mscoutermarsh** [comment]
Hi @Eomm - this is a bug on our end, we're tracking internally and will fix.

Thanks!

**Comment by andymckay** [comment]
We think this is fixed now. Please let us know if this isn't the case, thank you @Eomm 🙇
