### ISSUE TITLE
receiving yaml error: bad indentation of a mapping entry on yarn build 

### ISSUE THREAD

**Issue by Jahanzaiib** [actions/starter-workflows#653]
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with: 
          version:12
          
          
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          # Yarn command
          cmd: install # yarn install/npm install
          
        -name: Creating Build
         run: yarn build
         
         # Runs a set of commands using the runners shell
      - name: Installing surge
        run: npm install -g surge 
        
      - name: deploying using surge 
        run: surge ./ http://jazibootcamp2.surge.sh/ --token ${{secrets.SECRET_SURGE}}

**Comment by brownsteward** [comment]
I haven't been on git hub for months,I think someone has hacked my
account,this isn't the only app I'm having issues with,I cant even get into
my samsung account,Google says get a new account,well I shouldn't have to
get a new account,I'm not very computer literate  and have worked hard on
getting  where I am now,is there anything got hub can do to help ,point in
in the direction of someone who can?thank you

**Comment by nursenamo** [comment]
> # This is a basic workflow to help you get started with Actions
> 
> name: CI
> # Controls when the action will run. Triggers the workflow on push or pull request
> # events but only for the master branch
> 
> on:
> push:
> branches: [ master ]
> pull_request:
> branches: [ master ]
> # A workflow run is made up of one or more jobs that can run sequentially or in parallel
> 
> jobs:
> # This workflow contains a single job called "build"
> 
> build:
> # The type of runner that the job will run on
> runs-on: ubuntu-latest
> 
> ```
> # Steps represent a sequence of tasks that will be executed as part of the job
> steps:
>   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
>   - uses: actions/checkout@v2
> 
>   - name: Setup Node.js environment
>     uses: actions/setup-node@v2-beta
>     with: 
>       version:12
>       
>       
>   - name: GitHub Action for Yarn
>     uses: Borales/actions-yarn@v2.3.0
>     with:
>       # Yarn command
>       cmd: install # yarn install/npm install
>       
>     -name: Creating Build
>      run: yarn build
>      
>      # Runs a set of commands using the runners shell
>   - name: Installing surge
>     run: npm install -g surge 
>     
>   - name: deploying using surge 
>     run: surge ./ http://jazibootcamp2.surge.sh/ --token ${{secrets.SECRET_SURGE}}
> ```

#653
