### ISSUE TITLE
Use GITHUB_TOKEN to auth in docker.pkg.github.com

### ISSUE THREAD

**Issue by MikeVL** [actions/starter-workflows#66]
Try to publish docker container to docker.pkg.github.com

I got error: Error response from daemon: login attempt to https://docker.pkg.github.com/v2/ failed with status: 401 Unauthorized

```
name: Deploy

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: login
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by judge2020** [comment]
Sent a support request to GitHub about 2 weeks ago (ticket id 349594) regarding this and still awaiting a response.

I've tried the following, all with 401 unauthorized:

* `publisher` (from [the keynote](https://youtu.be/E1OunoCyuhY?t=1323), but here they use a dedicated PAT)
* `x-oauth-basic`
* `x-access-token` ([from here](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation))
* `${GITHUB_ACTOR}`
* the org name when running actions within an org-owned repository.

And to be clear, [this help page](https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret) says the `GITHUB_TOKEN` token has "packages read/write" permission.

![image](https://user-images.githubusercontent.com/8601934/63893077-395b6580-c9b7-11e9-97b7-9d0c013904b0.png)

**Comment by judge2020** [comment]
Got this back:

> Hi Hunter,
> 
> > I was wondering what the username should be (basic auth) when using an integration token when pushing docker images to GitHub package repository. Based on this docs page, the token should have the read/write packages permission, but I'm not sure what username to use while authenticating with Docker.
> 
> Sorry for the delay, and thanks for reaching out! That's a great question to which we don't have any documentation for (yet!). I've asked our engineering team for an assist with this and we will follow up with you once we hear more from them.
> 
> All the best,
> Francis

**Comment by judge2020** [comment]
Another reply:

> Our team got back to us and let us know that the username can be anything you'd like. However, we suggest using a personal access token instead of the GITHUB_TOKEN provided by Actions as Docker isn't supported at the moment.

So hopefully the ability to use this comes soon. For now, you can use a dedicated PAT with any username to login.

**Comment by landsman** [comment]
@judge2020 What you mean by PAT?

**Comment by judge2020** [comment]
@landsman A personal access token - for now, you can create one with the `write:packages` permission, and [store it in the secrets store](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables) to push to docker at this time. 

Based on the reply saying "Docker isn't supported at the moment", and that [this blog post](https://github.blog/changelog/2019-09-06-publishing-a-package-no-longer-creates-a-release-and-other-github-package-registry-updates/) added support for `GITHUB_TOKEN` usage to Nuget, I suspect the built-in `GITHUB_TOKEN` is planned to work for Docker in the future.

**Comment by sagikazarmark** [comment]
For me, the main value proposition of GitHub Actions is that everything is integrated under one umbrella. Until that's not true, it's not better than the competition who has their services up and running probably for years now. I understand that this is a beta program, but still, GitHub needs to "kick ass" if they want to enter this market. Otherwise it's just another service and there won't be any incentive in it for users to migrate their projects to GitHub Actions.

**Comment by pascalandy** [comment]
I don't agree

> Otherwise it's just another service and there won't be any incentive in it for users to migrate their projects to GitHub Actions.

**Comment by 1138-4EB** [comment]
> I don't agree

@pascalandy, I don't neither. At the same time, I do understand @sagikazarmark's concern/frustration, specially related to how security is being handled/communicated. AFAIU, the standard suggested procedure is to execute actions from the wild and provide them access to GITHUB_TOKEN by default. Considering that actions can be completely rewritten without prior notice and without an easy mechanism to detect it, I'd say that this is a serious issue.

Moreover, despite having to deal with that security issue, it does not help to make the chores easier. As @judge2020 commented above, for some features PATs are required yet. By the same token, if git push access is required only, a deployment key is a better fit than the GITHUB_TOKEN.

Don't take me wrong: I'm happily embracing GitHub Actions and I think there are many useful and unique features in the environment. Yet, it is frightening to think that this is going out from Beta in four weeks. Engineers at GH must be having a really hard time...

**Comment by ethomson** [comment]
>  I suspect the built-in GITHUB_TOKEN is planned to work for Docker in the future.

Correct, the GitHub Package Registry team is working on this.  The GITHUB_TOKEN will work for all GPR registries.

Since work is in progress on this, and it is not related to the starter workflows, I'm going to close this issue.  If you have additional questions, we're happy to discuss with you on the [GitHub Actions](https://github.community/t5/GitHub-Actions/bd-p/actions) board or you can [contact us](https://support.github.com/).

**Comment by sagikazarmark** [comment]
> > Otherwise it's just another service and there won't be any incentive in it for users to migrate their projects to GitHub Actions.

> I don't agree

@pascalandy @1138-4EB I'm not saying people _shouldn't_ use GitHub Actions without the package registry integration, all I'm saying is that without an all-in-one package it's probably less appealing to teams who have their workflow up and running on platforms built with years of experience in CI/CD. And everyone uses something, question is whether they are satisfied/ready to switch. Everyone is building a CI solution these days, so it's harder to enter the market without unique features.

Just to clarify what you are disagreeing with. 🙂

**Comment by landsman** [comment]
@ethomson Do you have estimate when will be Github Actions ready for using with Registry as been mentioned there? Thanks.

**Comment by 1138-4EB** [comment]
Quick update to report that the default GITHUB_TOKEN (the example that @MikeVL posted) is working for me. Unfortunately, shown registry urls are wrong, because they need to be lowercase. But apart from that, I can successfully login and push to the registry corresponding to the repo where the action is being executed: https://github.com/1138-4EB/vunit/commit/df6154246b1efec095483ffe6703f367ec47843d/checks?check_suite_id=278462741

Note that pushing to a different repository produces an internal server error after several retries: https://github.com/1138-4EB/vunit/runs/272227638#step:4:60

**Comment by stefan2904** [comment]
I can confirm that this works for me:
```json
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by RammusXu** [comment]
Good. Now we can do
```yaml

    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        IMAGE_NAME="docker.pkg.github.com/${GITHUB_REPOSITORY}/my-image:1.0"
        docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${{ github.token }}
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
```

**Comment by eine** [comment]
@RammusXu, why `${{ github.token }}` instead of `${{ secrets.GITHUB_TOKEN }}`? Do both contain the same value?

**Comment by RammusXu** [comment]
@eine It's same. Just shorter, lol.

**Comment by ozbillwang** [comment]
since the container registry has been changed to `ghcr.io`
```  
      - name: Login Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
```
