### ISSUE TITLE
CMake not linking C++ libraries

### ISSUE THREAD

**Issue by MCWertGaming** [actions/starter-workflows#669]
Hello,
Im creating an application with ncurses and i need to link ncurses as compiler flag. The C/C++ CMake starter workflow is running the right commands, i already checked that. The thing, is that 
```
cmake .
make
```
doesn't work in github actions, but on my machine (Fedora 32) it does with the same commands. 

Just doing 
```
g++ src/main.cpp -o test -lncurses
```
works perfectly fine, even in github actions itself. So my question is why CMake does not set the linking flag of ncurses?

This is the result of the starter workflow (i removed only the testing part):
CMake configuration:
```shell
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/runner/work/test/build
```
build:
```
Scanning dependencies of target test
[ 50%] Building CXX object CMakeFiles/test.dir/src/main.cpp.o
[100%] Linking CXX executable test
/usr/bin/ld: CMakeFiles/test.dir/src/main.cpp.o: in function `main':
main.cpp:(.text.startup+0x9): undefined reference to `initscr'
/usr/bin/ld: main.cpp:(.text.startup+0x17): undefined reference to `printw'
/usr/bin/ld: main.cpp:(.text.startup+0x1c): undefined reference to `refresh'
/usr/bin/ld: main.cpp:(.text.startup+0x23): undefined reference to `stdscr'
/usr/bin/ld: main.cpp:(.text.startup+0x28): undefined reference to `wgetch'
/usr/bin/ld: main.cpp:(.text.startup+0x2d): undefined reference to `endwin'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test.dir/build.make:101: test] Error 1
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/test.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
Error: Process completed with exit code 2.
```
My CmakeLists.txt:
```
cmake_minimum_required(VERSION 3.16)
project(test)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED true)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lncurses")

add_executable(test src/main.cpp)
```

Thank you for helping me!

**Comment by vantuan1994** [comment]
> Xin chào,
> Tôi đang tạo một ứng dụng với ncurses và tôi cần liên kết ncurses dưới dạng cờ trình biên dịch. Dòng công việc khởi động C / C ++ CMake đang chạy các lệnh phù hợp, tôi đã kiểm tra điều đó. Điều này là
> 
> ```
> cmake .
> make
> ```
> 
> không hoạt động trong các hành động github, nhưng trên máy của tôi (Fedora 32) nó hoạt động với các lệnh tương tự.
> 
> Vừa làm
> 
> ```
> g++ src/main.cpp -o test -lncurses
> ```
> 
> hoạt động hoàn toàn tốt, ngay cả trong chính các hành động trên github. Vì vậy, câu hỏi của tôi là tại sao CMake không đặt cờ liên kết của ncurses?
> 
> Đây là kết quả của quy trình làm việc khởi động (tôi chỉ loại bỏ phần thử nghiệm):
> Cấu hình CMake:
> 
> ```shell
> - Nhận dạng trình biên dịch C là GNU 9.3.0
> - Nhận dạng trình biên dịch CXX là GNU 9.3.0
> - Kiểm tra cho trình biên dịch C làm việc: / usr / bin / cc
> - Kiểm tra đối với công tác biên dịch C: / usr / bin / cc - công trình
> - Phát hiện thông tin ABI của trình biên dịch C
> - Phát hiện thông tin ABI của trình biên dịch C - đã xong
> - Phát hiện các tính năng biên dịch C
> - Phát hiện C biên dịch các tính năng - thực hiện 
> - Kiểm tra đối với công tác biên dịch CXX: / usr / bin / c ++
> - Kiểm tra cho trình biên dịch CXX làm việc: / usr / bin / c ++ - công trình
> - Phát hiện thông tin ABI của trình biên dịch CXX
> - Phát hiện thông tin ABI của trình biên dịch CXX - đã xong
> - Phát hiện các tính năng biên dịch CXX
> - Phát hiện CXX tính năng biên dịch - thực hiện 
> - Cấu hình thực hiện 
> - Tạo thực hiện 
> - file xây dựng đã được ghi vào: / home / Á hậu / công việc / thử nghiệm / xây dựng
> ```
> 
> xây dựng:
> 
> ```
> Scanning dependencies of target test
> [ 50%] Building CXX object CMakeFiles/test.dir/src/main.cpp.o
> [100%] Linking CXX executable test
> /usr/bin/ld: CMakeFiles/test.dir/src/main.cpp.o: in function `main':
> main.cpp:(.text.startup+0x9): undefined reference to `initscr'
> /usr/bin/ld: main.cpp:(.text.startup+0x17): undefined reference to `printw'
> /usr/bin/ld: main.cpp:(.text.startup+0x1c): undefined reference to `refresh'
> /usr/bin/ld: main.cpp:(.text.startup+0x23): undefined reference to `stdscr'
> /usr/bin/ld: main.cpp:(.text.startup+0x28): undefined reference to `wgetch'
> /usr/bin/ld: main.cpp:(.text.startup+0x2d): undefined reference to `endwin'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/test.dir/build.make:101: test] Error 1
> make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/test.dir/all] Error 2
> make: *** [Makefile:101: all] Error 2
> Error: Process completed with exit code 2.
> ```
> 
> CmakeLists.txt của tôi:
> 
> ```
> cmake_minimum_required(VERSION 3.16)
> project(test)
> 
> set(CMAKE_CXX_STANDARD 20)
> set(CMAKE_CXX_STANDARD_REQUIRED true)
> 
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lncurses")
> 
> add_executable(test src/main.cpp)
> ```
> 
> Cảm ơn vì đã giúp tôi!
