### ISSUE TITLE
Add an icon to 'Manual workflow'

### ISSUE THREAD

**Issue by jenschelkopf** [actions/starter-workflows#728]
Let's add an icon to 'Manual workflow' to make it look nicer on the New Workflow page.

Here's what it looks like now:
![image](https://user-images.githubusercontent.com/1865328/100891896-5f579b80-347f-11eb-92b1-a18ac2ed6995.png)

Since manual workflows are most often used so that a human can trigger a workflow, I think we should use the 'person' icon:

![Screen Shot 2020-12-02 at 9 19 35 AM](https://user-images.githubusercontent.com/1865328/100892015-7f875a80-347f-11eb-85da-4889df60bc18.png)

**Comment by andymckay** [comment]
Fixed in https://github.com/actions/starter-workflows/pull/736
