### ISSUE TITLE
Laravel action - error on Installing Dependencies

### ISSUE THREAD

**Issue by TheBikramLama** [actions/starter-workflows#747]
There seems to be a bug or update on Github's side, Laravel action is failing on "Installing Dependencies". The error message reads:
```
Run composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
Your lock file does not contain a compatible set of packages. Please run composer update.
Error: Process completed with exit code 2.
```

**Comment by TheBikramLama** [comment]
Update: I think GitHub is using PHP 8 by default, which is causing the issues
```
Problem 1
    - Root composer.json requires lcobucci/jwt == 3.3.3.0 -> satisfiable by lcobucci/jwt[3.3.3].
    - lcobucci/jwt 3.3.3 requires php ^5.6 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
...
```

**Comment by atasciuc** [comment]
Facing the same issue.

**Comment by mamulazmi** [comment]
yep, i experience same issue

**Comment by sagegwatkin** [comment]
Was also facing this issue today, and found a fix for it.

I used the [shivammathur/setup-php](https://github.com/shivammathur/setup-php) package to specify the PHP version used in the action.

Edit your action file (_laravel.yml_), and insert a step after the checkout step, to setup PHP with the version that you require:

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Node Dependencies
      run: npm install

**Comment by ninthday** [comment]
Thanks, It's work for me.

**Comment by hallowcard13** [comment]
@sagegwatkin thank you

**Comment by andymckay** [comment]
PHP was updated to 8.0. I've merged https://github.com/actions/starter-workflows/pull/748 to include `setup-php` which hopefully fixes this problem.

**Comment by andymckay** [comment]
Please re-open if its still a problem or we need to do more work here, thanks!

**Comment by MartinMontanari** [comment]
People like you makes the world a better place!! Thanks my friend, you save me @sagegwatkin!!

**Comment by basitbiz** [comment]
@sagegwatkin thanks, it worked smoothly

**Comment by peterdudfield** [comment]
I found this to be an issue. I set up the default workflow and it failed. 
https://github.com/materiom/materiom_v1/runs/4833372366?check_suite_focus=true

I also tried the change above but with no luck. Has there been an update of some sort? Or perhaps I've done something silly.

**Comment by Jacos-Monjur** [comment]
Thanks That's work

**Comment by kirubidavid** [comment]
I found a solution by actually following the instruction requested. I added Composer Update on my **laravel.yml** and it now works.

```
      name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update composer
      run: composer update
    - name: Install Dependencies
```

**Comment by Shaz3e** [comment]
name: Update composer throwing an error any fixes

**Comment by muhammadmp97** [comment]
I fixed the problem by changing the PHP version:
```
+ php-version: '8.1'
```

**Comment by macocci7** [comment]
I fixed the problem by

 `composer  update` in the lowest PHP version

 which the repository supports (8.0 in my case)

before `git add` at local environment.

![github_actions_php8 0](https://github.com/actions/starter-workflows/assets/19181121/04750d2c-1ac9-4057-b164-b7e98796fae0)

**Comment by renepardon** [comment]
Running `composer update` feels wrong because the dependencies change for this build and tests only. There must be another solution on this.

I also use it like this for now without success:

```yaml
- uses: actions/checkout@v3
- uses: shivammathur/setup-php@v2
  with:
    php-version: '8.2'
```

**Comment by evandroafonso** [comment]
Updated to the right version of PHP works for me. In my case I changed:
`php-version: '8.0'` to `php-version: '8.3.2'`
Thanks!!
