### ISSUE TITLE
How i can setup workflow status badge status on README.md

### ISSUE THREAD

**Issue by nibro7778** [actions/starter-workflows#75]
Hi Team,

First of all its not an issue. I couldn't find any source which can help me to setup status badge on README.md file. I just started with GitHub action workflow and try to implement in my few open-source repositories. Is there any way where I can set up a workflow status badge on README.md file.

https://github.com/actions/setup-dotnet/workflows/Main%20workflow/badge.svg

Thanks,
Niraj Trivedi

**Comment by mendhak** [comment]
I couldn't find any docs on this either, hope it's coming soon.  Your repo is a bit of a weird one.  I was able to get at a badge for the ASP.NET Core CI

https://github.com/nibro7778/mydiary/workflows/ASP.NET%20Core%20CI/badge.svg

But not your newer one, dotnet-core-build

https://github.com/nibro7778/mydiary/workflows/dotnet-core-build/badge.svg

Is the 'dotnet-core-build' a renamed version of the original ASP.NET Core CI?

**Comment by nibro7778** [comment]
Yes, I have created a new workflow with name `dotnet-core-build` please find a reference from [here ](https://github.com/nibro7778/mydiary/actions)

**Comment by andymckay** [comment]
Thank you @nibro7778, but we'd like to keep issues related to code in this repository.

* If you have questions about writing workflows or action files, then please visit the GitHub Community Forum's Actions Board
* If you are having an issue or question about GitHub Actions then please contact customer support

There is a known issue about badges being shown for branches, it just works for master at the moment, we are working on that and should have a fix shortly.
