### ISSUE TITLE
code-scanning README.md link 404

### ISSUE THREAD

**Issue by Aikenwu** [actions/starter-workflows#781]
Enabling Code Scanning for a repository link error 404 code.
https://github.com/actions/starter-workflows/blob/5760418d4f378a531680d729f4bf0b73eea45822/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository 

Here is the right link? 
https://docs.github.com/en/enterprise-server@2.22/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

**Comment by Rkbhasan1** [comment]
https://docs.github.com/en/enterprise-server@2.22/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

**Comment by Rkbhasan1** [comment]
Thanks.
