### ISSUE TITLE
Github Actions Android workflow failing

### ISSUE THREAD

**Issue by amit-thakur-S** [actions/starter-workflows#786]
Our workflow on Github Actions is consistently failing for the last 12 days on master branch. However, the same workflow ran successfully on a WIP branch created from master with the same yml. The difference is, we made a commit on WIP which triggered the workflow and we rerun the failed job on master.

Failure usually occurs on Tests and the reasons are inconsistent. We use Mac OS X to build and test the code and malinskiy/action-android/install-sdk@release/0.1.0 to install android sdk. Any suggestions?

**Comment by AverageComet250** [comment]
Try porting your workflows to Linux as it will be cheaper and, issues may be caused because of the work flows being run on MacOS. For your info, MacOS runners are around 20x costlier than Linux runners.

**Comment by amit-thakur-S** [comment]
Thanks @AverageComet250 Seems like a good suggestion.

Any idea why it fails on MacOS so often?

**Comment by AverageComet250** [comment]
Not really.

I've never used a Mac for programming, as I run all my workloads on Windows 10 + WSL2.

That setup allows me to develop for Windows and Linux easily, but like I said, I've never developed for or on a Mac. If I can have view access to your repository I might be able to work it out.

But the only reason to use a Mac runner is when you need to use xcode to build for an apple platform.

**Comment by konradpabjan** [comment]
Please direct questions like this to our community forum: https://github.community/c/code-to-cloud/github-actions/41

Issues in this repositories should only be related to our starter workflows 🙇‍♂️

If you're experiencing issues with our hosted runners like MacOS, please look for open issues or open an issue in: https://github.com/actions/virtual-environments
