### ISSUE TITLE
action auto install docker in server and deploy 

### ISSUE THREAD

**Issue by AronWaterAron** [actions/starter-workflows#789]
Are there any action that could ssh to check whether the target server has docker install,
if not install it,
and deploy the project as a container?

**Comment by konradpabjan** [comment]
Please direct questions like this to our community forum: https://github.community/c/code-to-cloud/github-actions/41

Issues in this repository should only be related to our starter workflows 🙇‍♂️

(Regarding SSHing into a runner, check out this: https://github.com/mxschmitt/action-tmate, not official, but it gets the job done)
