### ISSUE TITLE
python-publish.yml doesn't read username from secrets variable

### ISSUE THREAD

**Issue by johnpaulkiser** [actions/starter-workflows#791]
```
EOFError: EOF when reading a line
Enter your username: 
Error: Process completed with exit code 1.

```
 👆 This is is the error it returns. Any clue why this is doing this?

**Comment by johnpaulkiser** [comment]
This was my fault. I didn't realize that re-running the action wasn't taking into account changes that I made to the .yml since the original action was triggered. 

Is there a way to manually re-trigger an action for debugging purposes?

**Comment by AverageComet250** [comment]
Just make a file for workflow debugging and edit it whenever you want to test a new workflow. The file can be named anything and have any extension.
