### ISSUE TITLE
Triggering workflows when downstream jobs complete

### ISSUE THREAD

**Issue by sd185233** [actions/starter-workflows#794]
Is there any way for Workflows to trigger when downstream dependency jobs complete?  

I can see it's possible to use workflow_dispatch to invoke workflows in other repos, so could have downstream workflows trigger upstream jobs - but this would mean hard coding a list of many upstream jobs in our lower level library jobs, instead of having workflows "watch" certain jobs for triggering and finishing.  For example, our CI build should be run if our Foundation library is rebuilt.

Is this possible or is it something that will be available in the future?

**Comment by kkash18** [comment]
> Is there any way for Workflows to trigger when downstream dependency jobs complete?  
> 
> I can see it's possible to use workflow_dispatch to invoke workflows in other repos, so could have downstream workflows trigger upstream jobs - but this would mean hard coding a list of many upstream jobs in our lower level library jobs, instead of having workflows "watch" certain jobs for triggering and finishing.  For example, our CI build should be run if our Foundation library is rebuilt.
> 
> Is this possible or is it something that will be available in the future?

**Comment by kkash18** [comment]
> Is there any way for Workflows to trigger when downstream dependency jobs complete?  
> 
> I can see it's possible to use workflow_dispatch to invoke workflows in other repos, so could have downstream workflows trigger upstream jobs - but this would mean hard coding a list of many upstream jobs in our lower level library jobs, instead of having workflows "watch" certain jobs for triggering and finishing.  For example, our CI build should be run if our Foundation library is rebuilt.
> 
> Is this possible or is it something that will be available in the future?

![00ae.png](https://user-images.githubusercontent.com/77268170/107900518-cfb27c80-6f06-11eb-921f-091b42050e63.png)

**Comment by kkash18** [comment]
https://www.github.com/kkash18/docs/tree/main/.vscode%2Flaunch.json

**Comment by konradpabjan** [comment]
Please direct questions like this to our community forum: https://github.community/c/code-to-cloud/github-actions/41

Issues in this repository should only be related to our starter workflows 🙇‍♂️

(You can use `workflow_dispatch` with a PAT to trigger workflows downstream. Workflows triggered using `GITHUB_TOKEN` are ignored as it's very easy to create infinite loops of workflows)
