### ISSUE TITLE
How to securely login through Docker CLI

### ISSUE THREAD

**Issue by eine** [actions/starter-workflows#818]
Refs:

- actions/starter-workflows#96
- docker/login-action#30

**Comment by eine** [comment]
This is still relevant.

**Comment by ivan0117** [comment]
P

**Comment by ivan0117** [comment]
N

**Comment by eine** [comment]
Still unsolved.

**Comment by eine** [comment]
Still unsolved.

**Comment by eine** [comment]
Still unsolved.

**Comment by Phantsure** [comment]
@eine Can you please tell what is keeping this issue open?

**Comment by eine** [comment]
@Phantsure if you do `docker login` in a Github Actions workflow you get the following warning message:

```
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

If you use the docker/login-action image, the same warning is produced, but it is hidden from the user (see https://github.com/docker/login-action/pull/25).

There is no documented solution to store the password non unencrypted.

**Comment by eine** [comment]
AFAIAA this issue is still relevant.
