### ISSUE TITLE
I’m lost

### ISSUE THREAD

**Issue by Jacobtarango21** [actions/starter-workflows#828]

**Comment by MrGithub2021** [comment]
Yea, I'm also lost on something else; The Swift GitHub Actions
First, I used the Swift template and made a pull request
Second, I merged it
Third, I see an error
Here is the error:
![image](https://user-images.githubusercontent.com/77593158/110817655-80880f00-825a-11eb-9c01-1ccaaf59c0c7.png)
Can you please help?
