### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MrGithub2021** [actions/starter-workflows#836]
Hello actions, I am MrGithub2021 and I am lost on Swift Github Actions
Here are the things that i did:
First, I picked the Swift workflow:
![image](https://user-images.githubusercontent.com/77593158/110835007-40318c80-826c-11eb-980f-fce86d004f0c.png)
Second, I created it:
![image](https://user-images.githubusercontent.com/77593158/110835086-593a3d80-826c-11eb-940f-05e4e5059688.png)
Third, I made a pull request:
![image](https://user-images.githubusercontent.com/77593158/110835204-80910a80-826c-11eb-8e7f-a5c234a6d9c3.png)
Fourth, I merged the changes:
![image](https://user-images.githubusercontent.com/77593158/110835258-91da1700-826c-11eb-9e67-7dfaef473a13.png)
Finally, I get an error:
![image](https://user-images.githubusercontent.com/77593158/110835341-a9190480-826c-11eb-8c94-5e0de8a01cd1.png)
It says that there is no "root manifest."
Can you please help? I would love if you did.

**Comment by AverageComet250** [comment]
How do you normally build your app?

**Comment by MrGithub2021** [comment]
@AverageComet250 
Here is my simple project; it is an app that tells you 5 questions: [My Project](https://github.com/MrGithub2021/MyTestApp)

**Comment by MrGithub2021** [comment]
@AverageComet250 
I just put the source code there, in my project.
I don't have any deploying tools other than some playgrounds.

**Comment by AverageComet250** [comment]
I think you need a package.swift file, but I've never used swift so I can't be sure.

**Comment by MrGithub2021** [comment]
Ok..... I will make a branch and try renaming the file.

**Comment by MrGithub2021** [comment]
Wait, I already have one.

**Comment by MrGithub2021** [comment]
And it failed.

**Comment by MrGithub2021** [comment]
I think I need XCode to do this.

**Comment by MrGithub2021** [comment]
So, no Swift for me : (

**Comment by MrGithub2021** [comment]
Wait, what if you and I work together?

**Comment by AverageComet250** [comment]
Sorry about leaving you hanging, I've been kinda busy recently and I haven't been checking my mail.

Anyway, when you created your project, you should've done

swift package init --type executable

Which then means you can build your swift package into an executable using

swift build

Also you HAVE to have a file named main.swift in your main package.

Thanks,
Shravan Mandava

________________________________

**Comment by AverageComet250** [comment]
@MrGithub2021 I've gone through your code and I think you've incorrectly structured your code. Can you pull the latest copy of your code and attempt to build it on your local machine

**Comment by MrGithub2021** [comment]
What? I am just a beginner dev.
