### ISSUE TITLE
Triggering workflow only for one Issue 

### ISSUE THREAD

**Issue by ibakshay** [actions/starter-workflows#89]
Hi, 

For my use-case, I need to trigger the workflow only one specific `issue`, for example let's say for issue number 5,  https://github.com/user/repo/issues/5 and not for any other issues. 

Can you please tell me how can I configure the workflow YML file for this use-case ?.

**Comment by chrispat** [comment]
That is not currently possible.  More options for filtering events is something we want to have in the future.

**Comment by ibakshay** [comment]
That will be great. Thank you for your response
