### ISSUE TITLE
Guidelines for Contributing new templates

### ISSUE THREAD

**Issue by larshp** [actions/starter-workflows#91]
Hi,
What is the process for adding new templates? Do you accept pull requests for languages currently not supported?

https://github.com/actions/starter-workflows/blob/master/CONTRIBUTING.md seems empty?

**Comment by larshp** [comment]
yea, just worried that the "new" page will turn into a big mess, https://github.com/actions/starter-workflows/actions/new

and what is the relation for starter flows vs the marketplace, https://github.com/marketplace?type=actions

I'm considering adding a starter workflow for ABAP, which is not a very popular language on GitHub(yet), adding all languages to the starter workflows will give a very long list, and perhaps not help users very much.

💡 one suggestion: the starter workflows suggested should suggest the actions corresponding to the main programming languages in the repository?

**Comment by mscoutermarsh** [comment]
> 💡 one suggestion: the starter workflows suggested should suggest the actions corresponding to the main programming languages in the repository?

Yes, that's how it works currently. The top row shows Workflows that are relevant to your repository.

We aren't accepting everything into this repo at the moment because of exactly the issue you mentioned. We'll be improving this. For now we're prioritizing the most used languages on GitHub.

**Comment by larshp** [comment]
Agree, but suggest clarifying in the contributing guidelines, https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

In my case I would like to add a setup for a lesser popular language(ABAP), would this be considered okay since there are no existing template setups?

**Comment by mscoutermarsh** [comment]
guidelines have been added
