### ISSUE TITLE
BUG: Merging on branch master actually rebuilds other branches as well.

### ISSUE THREAD

**Issue by pascalandy** [actions/starter-workflows#92]
I think there is a **bug** impacting `on`. 

### scenario

- I'm working on **edge** branch
- I do a change commit & push
- Merge to **master** branch & push

### The issue

Github actions CI builds both **master** and **edge** branches at the same time. In my YAML, the rule is clear, build **master** (and nothing else).

Also, the same behavior happen when I merge code from master into edge.

It's very important in my case as:
- I want to push **edge tag** to my docker registry for any branches (but not master)
- I want to push **stable tag** to my docker registry on for commits on master.

### screenshot

![Screen Shot 2019-09-02 at 2 55 15 PM](https://user-images.githubusercontent.com/6694151/64130829-dee54f00-cd92-11e9-9d6f-45b0b4836f10.jpg)

You can checkout [my repo here](https://github.com/firepress-org/noti-in-docker/actions).

**Comment by andymckay** [comment]
Thank you @pascalandy, but we'd like to keep issues related to code in this repository.

* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

**Comment by Alessthana** [comment]
Have you found a solution for this? thanks.
