### ISSUE TITLE
Allow me to hide or remove older workflows

### ISSUE THREAD

**Issue by pascalandy** [actions/starter-workflows#93]
I have two workflows. It's kind of ugly to see older ones. 
Suggestion: Please, hide them by default.

![Screen Shot 2019-09-02 at 3 10 54 PM](https://user-images.githubusercontent.com/6694151/64131035-025cc980-cd94-11e9-8553-7522b6ec2019.jpg)

**Comment by mscoutermarsh** [comment]
Thanks @pascalandy! We have a few upgrades coming to that page in the next couple weeks. This problem is on the list.

**Comment by mscoutermarsh** [comment]
Fix to this has been shipped. Thanks everyone!

**Comment by pascalandy** [comment]
Thanks!

For some reason, on this view the newest build is at the bottom. They should be at the top.
![Screen Shot 2019-09-26 at 8 56 23 PM](https://user-images.githubusercontent.com/6694151/65734273-30d27980-e0a0-11e9-85c9-8e577d645e95.jpg)

**Comment by mscoutermarsh** [comment]
Fix for that is going out tonight. 👍


________________________________
